"""GENERATED by tools/generate.py from VoiceBlender openapi.yaml + asyncapi.yaml.

DO NOT EDIT — run ``make generate`` to regenerate.
"""

from __future__ import annotations

import json
from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from voiceblender._requests import ChannelInfo, OfferedCodec, ParticipantInfo, SIPRECStream, STTWord


class Event(BaseModel):
    """Base envelope for all webhook / VSI events."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    type: str
    timestamp: datetime
    instance_id: str | None = None


class LegRingingEvent(Event):
    """Fired when: sIP call ringing (inbound or outbound)"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None
    # Leg type (e.g. sip_inbound, sip_outbound)
    leg_type: str | None = None
    # Dialed SIP URI (outbound only)
    uri: str | None = None
    # Caller URI (inbound) or From header value (outbound, if set)
    from_: str | None = Field(default=None, alias="from")
    # Callee URI (inbound only)
    to: str | None = None
    # X-* custom SIP headers, if present
    sip_headers: dict[str, str] | None = None
    offered_codecs: list[OfferedCodec] | None = None
    trunk_id: str | None = None
    source_address: str | None = None
    authenticated: bool | None = None
    auth_username: str | None = None


class LegEarlyMediaEvent(Event):
    """Fired when: outbound leg received 183 Session Progress with SDP; media pipeline active"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None
    # Leg type (e.g. sip_outbound)
    leg_type: str | None = None


class LegConnectedEvent(Event):
    """Fired when: leg answered/connected"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None
    # Leg type (e.g. sip_inbound, sip_outbound, webrtc)
    leg_type: str | None = None


class LegDisconnectedEventCdr(BaseModel):
    """LegDisconnectedEventCdr."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Disconnect reason. Common SIP failures are mapped to named reasons; unmapped 4xx/5xx/6xx codes appear as sip_{code}. This is an open set — treat an unrecognized value as a new reason rather than an error. Known values: api_hangup, room_deleted, remote_bye, caller_cancel, max_duration, session_expired, rtp_timeout, busy, declined, rejected, unavailable, not_found, forbidden, server_error, ring_timeout, unauthorized, timeout, cancelled, not_acceptable, service_unavailable, invite_failed, connect_failed, challenged, transfer_completed, transfer_originate_failed, transfer_connect_failed, bad_answer, siprec_answer_failed, mixer_panic, hangup, peer_slow, connection_reset, ws_error, ws_dial_failed, moq_error, ice_failure, ice_failed, ice_disconnected, livekit_client_initiated, livekit_duplicate_identity, livekit_server_shutdown, livekit_kicked, livekit_room_deleted, livekit_state_mismatch, livekit_join_failure, livekit_migration, livekit_signal_close, livekit_room_closed, livekit_user_unavailable, livekit_user_rejected, livekit_token_expired, livekit_media_failure, livekit_disconnected, livekit_client_closed, livekit_signal_closed, livekit_signal_error, livekit_pc_setup_failed, livekit_add_track_failed, livekit_publisher_failed, livekit_subscriber_failed, livekit_signal_loop_exit, livekit_set_remote_desc_failed, livekit_create_answer_failed, livekit_set_local_desc_failed, livekit_signal_send_failed, livekit_set_publisher_remote_failed, livekit_participant_left.
    reason: str
    # Seconds from leg creation to disconnect
    duration_total: float
    # Seconds from answer to disconnect (0 if never answered)
    duration_answered: float


class LegDisconnectedEventQuality(BaseModel):
    """RTP quality metrics. Omitted for WebRTC legs or unanswered legs with no media."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Mean Opinion Score (1.0–5.0) estimated via simplified E-model (ITU-T G.107) from packet loss and jitter
    mos_score: float
    # Total inbound RTP audio packets received
    rtp_packets_received: int
    # Estimated lost packets based on sequence number gaps
    rtp_packets_lost: int
    # Inter-arrival jitter in milliseconds (RFC 3550 §A.8)
    rtp_jitter_ms: float


class LegDisconnectedEvent(Event):
    """Fired when: leg hung up (CDR-style nested structure)"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None
    cdr: LegDisconnectedEventCdr | None = None
    # RTP quality metrics. Omitted for WebRTC legs or unanswered legs with no media.
    quality: LegDisconnectedEventQuality | None = None


class LegJoinedRoomEvent(Event):
    """Fired when: leg added to a room"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None


class LegLeftRoomEvent(Event):
    """Fired when: leg removed from a room"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None


class LegMutedEvent(Event):
    """Fired when: leg muted"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None


class LegUnmutedEvent(Event):
    """Fired when: leg unmuted"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None


class LegDeafEvent(Event):
    """Fired when: leg deafened (stops receiving room audio)"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    leg_id: str | None = None
    app_id: str | None = None


class LegUndeafEvent(Event):
    """Fired when: leg undeafened (resumes receiving room audio)"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    leg_id: str | None = None
    app_id: str | None = None


class LegHoldEvent(Event):
    """Fired when: leg put on hold (local or remote)"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None
    # Hold direction: "local" (we put them on hold) or "remote" (they put us on hold)
    leg_type: str | None = None


class LegUnholdEvent(Event):
    """Fired when: leg taken off hold (local or remote)"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None
    # Hold direction: "local" or "remote"
    leg_type: str | None = None


class LegCommandFailedEvent(Event):
    """Fired when: an asynchronous leg command (202 Accepted) failed during execution"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    leg_id: str | None = None
    app_id: str | None = None
    command: str | None = None
    error: str | None = None


class LegStreamAddedEvent(Event):
    """Fired when: an additional m=audio stream was negotiated on a live dialog"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    leg_id: str | None = None
    app_id: str | None = None
    stream_id: str | None = None
    mid: str | None = None
    direction: str | None = None
    lang: str | None = None
    room_id: str | None = None
    role: str | None = None
    reason: str | None = None


class LegStreamRemovedEvent(Event):
    """Fired when: an audio stream was disabled with a port-0 re-INVITE; its m-line slot survives as a tombstone"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    leg_id: str | None = None
    app_id: str | None = None
    stream_id: str | None = None
    mid: str | None = None
    direction: str | None = None
    lang: str | None = None
    room_id: str | None = None
    role: str | None = None
    reason: str | None = None


class LegStreamRejectedEvent(Event):
    """Fired when: the peer refused an additional audio stream, or it could not be negotiated; the call is unaffected"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    leg_id: str | None = None
    app_id: str | None = None
    stream_id: str | None = None
    mid: str | None = None
    direction: str | None = None
    lang: str | None = None
    room_id: str | None = None
    role: str | None = None
    reason: str | None = None


class LegStreamFailedEvent(Event):
    """Fired when: an audio stream's media loop failed and the stream was torn down; the call continues on its remaining streams"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    leg_id: str | None = None
    app_id: str | None = None
    stream_id: str | None = None
    mid: str | None = None
    direction: str | None = None
    lang: str | None = None
    room_id: str | None = None
    role: str | None = None
    reason: str | None = None


class LegStreamRoomChangedEvent(Event):
    """Fired when: an audio stream was attached to or detached from a room (an empty room_id means detached)"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    leg_id: str | None = None
    app_id: str | None = None
    stream_id: str | None = None
    mid: str | None = None
    direction: str | None = None
    lang: str | None = None
    room_id: str | None = None
    role: str | None = None
    reason: str | None = None


class LegStreamRoleChangedEvent(Event):
    """Fired when: an audio stream's routing role changed; the room's allow-sets were recomputed atomically"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    leg_id: str | None = None
    app_id: str | None = None
    stream_id: str | None = None
    mid: str | None = None
    direction: str | None = None
    lang: str | None = None
    room_id: str | None = None
    role: str | None = None
    reason: str | None = None


class SIPRECSessionStartedEvent(Event):
    """Fired when: an inbound SIPREC recording session was accepted; carries the participants and the stream-to-participant bindings"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    leg_id: str | None = None
    app_id: str | None = None
    session_id: str | None = None
    data_mode: str | None = None
    participants: list[ParticipantInfo] | None = None
    streams: list[SIPRECStream] | None = None


class SIPRECSessionEndedEvent(Event):
    """Fired when: a SIPREC recording session ended"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    leg_id: str | None = None
    app_id: str | None = None
    session_id: str | None = None
    reason: str | None = None


class SIPRECMetadataUpdatedEvent(Event):
    """Fired when: a SIPREC recording session's metadata document was updated on a re-INVITE"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    leg_id: str | None = None
    app_id: str | None = None
    session_id: str | None = None
    data_mode: str | None = None
    participants_joined: list[str] | None = None
    participants_left: list[str] | None = None
    streams_added: list[str] | None = None
    streams_removed: list[str] | None = None
    streams: list[SIPRECStream] | None = None


class SIPRECParticipantJoinedEvent(Event):
    """Fired when: a party joined the call being recorded by a SIPREC session"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    leg_id: str | None = None
    app_id: str | None = None
    session_id: str | None = None
    label: str | None = None
    leg_stream_id: str | None = None
    participant_id: str | None = None
    participant_aor: str | None = None
    participant_name: str | None = None


class SIPRECParticipantLeftEvent(Event):
    """Fired when: a party left the call being recorded by a SIPREC session"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    leg_id: str | None = None
    app_id: str | None = None
    session_id: str | None = None
    label: str | None = None
    leg_stream_id: str | None = None
    participant_id: str | None = None
    participant_aor: str | None = None
    participant_name: str | None = None


class DTMFReceivedEvent(Event):
    """Fired when: dTMF digit received"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None
    # DTMF digit received
    digit: str | None = None
    seq: int | None = None


class RTTReceivedEvent(Event):
    """Fired when: real-Time Text (T.140 / RFC 4103) chunk received from the remote"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None
    # UTF-8 text chunk received from the remote
    text: str | None = None
    # Per-leg monotonic sequence (independent of RTP sequence numbers)
    seq: int | None = None
    # True when a U+FFFD has been prepended to indicate text was lost beyond what RFC 2198 redundancy could recover
    loss_marker: bool | None = None


class SpeakingStartedEvent(Event):
    """Fired when: participant started speaking"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier (present only when the leg is in a room)
    room_id: str | None = None
    app_id: str | None = None


class SpeakingStoppedEvent(Event):
    """Fired when: participant stopped speaking"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier (present only when the leg is in a room)
    room_id: str | None = None
    app_id: str | None = None


class PlaybackStartedEvent(Event):
    """Fired when: playback began"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None
    # Playback identifier
    playback_id: str | None = None


class PlaybackFinishedEvent(Event):
    """Fired when: playback ended"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None
    # Playback identifier
    playback_id: str | None = None
    # Why playback ended: 'completed' (reached the end of the audio) or 'stopped' (did not reach the end, for any reason)
    reason: str | None = None
    # Milliseconds of audio actually played, accumulated across repeat iterations
    played_ms: int | None = None


class PlaybackErrorEvent(Event):
    """Fired when: playback failed"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None
    # Playback identifier
    playback_id: str | None = None
    # Error message
    error: str | None = None


class TTSStartedEvent(Event):
    """Fired when: tTS synthesis began playing"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None
    # TTS playback identifier
    tts_id: str | None = None


class TTSFinishedEvent(Event):
    """Fired when: tTS synthesis finished playing"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None
    # TTS playback identifier
    tts_id: str | None = None
    # Why the utterance ended: 'completed' (reached the end of the audio) or 'stopped' (did not reach the end, for any reason)
    reason: str | None = None
    # Milliseconds of audio actually played
    played_ms: int | None = None


class TTSErrorEvent(Event):
    """Fired when: tTS synthesis or playback failed"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None
    # TTS playback identifier
    tts_id: str | None = None
    # Error message
    error: str | None = None
    # Failure category: permanent_auth, permanent_input, rate_limited, service_unavailable, retryable, canceled or unknown for a synthesis failure, playback for a failure while streaming the audio. New values may be added; treat an unrecognised value as unknown
    category: str | None = None


class TTSStagedEvent(Event):
    """Fired when: preflight TTS finished synthesizing and is ready to commit"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    room_id: str | None = None
    app_id: str | None = None
    # TTS playback identifier, to commit or discard
    tts_id: str | None = None
    # Size of the buffered audio
    bytes: int | None = None
    # How long the buffered audio will play for. 0 when the duration is not derivable from the audio format
    duration_ms: int | None = None


class TTSDiscardedEvent(Event):
    """Fired when: staged TTS was dropped without being played"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    room_id: str | None = None
    app_id: str | None = None
    # TTS playback identifier
    tts_id: str | None = None
    # Why the staged utterance was dropped: 'app' (explicitly discarded), 'expired' (TTS_PREFLIGHT_TTL elapsed) or 'leg_gone' (the leg ended while it was staged)
    reason: str | None = None


class RecordingStartedEvent(Event):
    """Fired when: recording began"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None
    # Recording file path or S3 URI — does not exist yet; the path only appears when the recording stops
    file: str | None = None


class RecordingFinishedEvent(Event):
    """Fired when: recording ended"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None
    # Recording file path or S3 URI
    file: str | None = None
    multi_channel_file: str | None = None
    channels: dict[str, ChannelInfo] | None = None
    # Participants whose audio is missing from multi_channel_file because their capture failed. Absent when the recording is complete
    omitted_legs: list[str] | None = None


class RecordingPausedEvent(Event):
    """Fired when: recording paused (audio replaced with silence)"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None
    file: str | None = None


class RecordingResumedEvent(Event):
    """Fired when: recording resumed from a paused state"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None
    file: str | None = None


class LegTransferInitiatedEvent(Event):
    """Fired when: we sent a SIP REFER (transfer initiated by the operator)"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None
    # Transfer kind: "blind" or "attended"
    kind: str | None = None
    # SIP URI to which the leg is being transferred
    target: str | None = None
    # Leg whose dialog is replaced (attended transfer only)
    replaces_leg_id: str | None = None


class LegTransferRequestedEvent(Event):
    """Fired when: we received a SIP REFER from the peer; decide via accept_transfer/decline_transfer (unless SIP_REFER_AUTO_DIAL=true)"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None
    # Transfer kind: "blind" or "attended"
    kind: str | None = None
    # SIP URI requested by the peer
    target: str | None = None
    # Call-ID present in the Refer-To Replaces parameter (attended only)
    replaces_call_id: str | None = None
    # Vestigial (always false); retained for wire compatibility. The outcome now flows via leg.transfer_completed / leg.transfer_failed after the app decides
    declined: bool | None = None


class LegTransferProgressEvent(Event):
    """Fired when: transfer progress reported via NOTIFY sipfrag"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None
    # Provisional SIP status from the NOTIFY sipfrag
    status_code: int | None = None
    # Reason phrase
    reason: str | None = None


class LegTransferCompletedEvent(Event):
    """Fired when: transfer reached terminal 2xx"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None
    # Final 2xx SIP status from the NOTIFY sipfrag
    status_code: int | None = None
    # Reason phrase
    reason: str | None = None


class LegTransferFailedEvent(Event):
    """Fired when: transfer failed (REFER rejected, sipfrag non-2xx, or local error)"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None
    # Final non-2xx SIP status (when applicable)
    status_code: int | None = None
    # Reason phrase
    reason: str | None = None
    # Local error message (when no SIP status applies)
    error: str | None = None


class RoomCreatedEvent(Event):
    """Fired when: room created"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Room identifier
    room_id: str | None = None
    app_id: str | None = None


class RoomDeletedEvent(Event):
    """Fired when: room deleted"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Room identifier
    room_id: str | None = None
    app_id: str | None = None


class RoomBridgedEvent(Event):
    """Fired when: two rooms' mixers were joined"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Bridge identifier
    bridge_id: str | None = None
    # First bridged room
    room_a_id: str | None = None
    # Second bridged room
    room_b_id: str | None = None
    app_id: str | None = None
    # Canonical direction relative to room_a_id: "bidirectional", "a_to_b", "b_to_a", or "none"
    direction: str | None = None


class RoomBridgeUpdatedEvent(Event):
    """Fired when: a bridge's audio flow direction changed"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Bridge identifier
    bridge_id: str | None = None
    # First bridged room
    room_a_id: str | None = None
    # Second bridged room
    room_b_id: str | None = None
    app_id: str | None = None
    # New canonical direction relative to room_a_id
    direction: str | None = None


class RoomUnbridgedEvent(Event):
    """Fired when: a bridge was torn down"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Bridge identifier
    bridge_id: str | None = None
    # First bridged room
    room_a_id: str | None = None
    # Second bridged room
    room_b_id: str | None = None
    app_id: str | None = None
    # Empty for an explicit delete, or "room_deleted" when a bridged room was deleted
    reason: str | None = None


class RoomRoutingChangedEvent(Event):
    """Fired when: the room's audio routing matrix changed"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    room_id: str | None = None
    app_id: str | None = None
    matrix: dict[str, list[str]] | None = None
    reason: str | None = None


class LegRoleChangedEvent(Event):
    """Fired when: a leg's routing role changed"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    leg_id: str | None = None
    room_id: str | None = None
    app_id: str | None = None
    old_role: str | None = None
    new_role: str | None = None


class STTTextEvent(Event):
    """Fired when: speech-to-text transcript"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None
    # Which of the leg's audio streams this came from. Empty when the leg's audio is the call itself; set for a recording session, where each stream is a different party. Resolve it through GET /v1/legs/{id}/siprec
    stream_id: str | None = None
    # Transcribed text
    text: str | None = None
    # Whether this is a final or partial transcript
    is_final: bool | None = None
    # Whether the speaker stopped talking, as opposed to is_final's 'this segment will not change again'. Deepgram only; always false for providers that do not report it
    speech_final: bool | None = None
    # Where in the stream this was said, in milliseconds from the first audio the transcriber was given. Absent when the provider reports no timing. Not the same as the event's arrival time, which is when the provider finished rather than when the words were spoken
    audio_start_ms: int | None = None
    # End of the span audio_start_ms opens
    audio_end_ms: int | None = None


class STTTurnEvent(Event):
    """Fired when: speech-to-text turn boundary"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None
    # Which of the leg's audio streams this turn belongs to. Empty when the leg's audio is the call itself. See stt.text.stream_id
    stream_id: str | None = None
    # Turn boundary: start_of_turn, update, eager_end_of_turn, turn_resumed or end_of_turn (Deepgram Flux), or utterance_end (Deepgram, when utterance_end_ms is set). New values may be added
    event: str | None = None
    # Index of the turn within the session, incrementing after each end_of_turn
    turn_index: int | None = None
    # Transcript of the turn so far. Empty on utterance_end
    text: str | None = None
    # How confident the model is that the turn has ended
    end_of_turn_confidence: float | None = None
    # Start of the audio window this transcript covers
    audio_window_start_ms: int | None = None
    # End of the audio window this transcript covers
    audio_window_end_ms: int | None = None
    # When the last word ended (utterance_end only)
    last_word_end_ms: int | None = None
    # Per-word transcript with timings and confidence, when the provider supplies it
    words: list[STTWord] | None = None
    # Languages detected in the turn
    languages: list[str] | None = None


class AgentConnectedEvent(Event):
    """Fired when: agent connected to provider"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None
    # Provider-assigned conversation identifier
    conversation_id: str | None = None


class AgentDisconnectedEvent(Event):
    """Fired when: agent session ended"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None


class AgentUserTranscriptEvent(Event):
    """Fired when: user speech transcribed by agent"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None
    # User speech text
    text: str | None = None


class AgentAgentResponseEvent(Event):
    """Fired when: agent generated a response"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None
    # Agent response text
    text: str | None = None


class AMDResultEvent(Event):
    """Fired when: answering machine detection completed"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None
    # Detection result: human, machine, no_speech, or not_sure
    result: str | None = None
    # Milliseconds of silence before first speech
    initial_silence_ms: int | None = None
    # Milliseconds of speech in the greeting
    greeting_duration_ms: int | None = None
    # Total milliseconds of analysis before determination
    total_analysis_ms: int | None = None


class AMDBeepEvent(Event):
    """Fired when: voicemail beep tone detected after machine classification"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None
    # Milliseconds from machine detection to beep tone detection
    beep_ms: int | None = None


class SIPRegistrationAttemptEvent(Event):
    """Fired when: inbound REGISTER surfaced for a challenge/accept/reject decision (auto-accepts on consult timeout)"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    app_id: str | None = None
    attempt_id: str | None = None
    aor: str | None = None
    contact: str | None = None
    source_address: str | None = None
    transport: str | None = None
    user_agent: str | None = None
    call_id: str | None = None
    has_authorization: bool | None = None


class SIPRegistrationActiveEvent(Event):
    """Fired when: sIP AOR registration created or refreshed (one event per Contact)"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    app_id: str | None = None
    # Canonical Address of Record (e.g. sip:alice@vb.example)
    aor: str | None = None
    # Contact URI registered by the UA
    contact: str | None = None
    # Transport-layer socket (ip:port) the REGISTER arrived on
    socket: str | None = None
    # Transport: udp | tcp | tls
    transport: str | None = None
    # User-Agent header from the REGISTER, if present
    user_agent: str | None = None
    # Call-ID of the most recent REGISTER
    call_id: str | None = None
    # Expiry granted to the binding (clamped to SIP_REGISTRATION_MAX_EXPIRES_SECONDS)
    granted_expires_seconds: int | None = None
    # Absolute expiry time (RFC 3339)
    expires_at: str | None = None


class SIPRegistrationExpiredEvent(Event):
    """Fired when: sIP AOR registration removed (TTL, explicit unregister, force-delete, or single-binding replacement)"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    app_id: str | None = None
    # Canonical Address of Record
    aor: str | None = None
    # Contact URI that was unbound
    contact: str | None = None
    # Transport-layer socket that held the binding
    socket: str | None = None
    # Why the binding was removed: ttl, unregistered, forced, or replaced
    reason: str | None = None


class SIPOutboundRegistrationActiveEvent(Event):
    """Fired when: outbound SIP trunk REGISTER accepted (initial or refresh)"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    app_id: str | None = None
    trunk_id: str | None = None
    aor: str | None = None
    registrar: str | None = None
    contact: str | None = None
    granted_expires_seconds: int | None = None
    expires_at: str | None = None
    call_id: str | None = None
    source_address: str | None = None


class SIPOutboundRegistrationFailedEvent(Event):
    """Fired when: outbound SIP trunk REGISTER failed (transport error, non-2xx response, or digest auth rejected)"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    app_id: str | None = None
    trunk_id: str | None = None
    aor: str | None = None
    registrar: str | None = None
    status_code: int | None = None
    reason: str | None = None
    error: str | None = None


class SIPOutboundRegistrationExpiredEvent(Event):
    """Fired when: outbound SIP trunk removed (DELETE, shutdown, or refresh failed past granted lifetime)"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    app_id: str | None = None
    trunk_id: str | None = None
    aor: str | None = None
    registrar: str | None = None
    reason: str | None = None


_EVENT_TYPES: dict[str, type[Event]] = {
    "leg.ringing": LegRingingEvent,
    "leg.early_media": LegEarlyMediaEvent,
    "leg.connected": LegConnectedEvent,
    "leg.disconnected": LegDisconnectedEvent,
    "leg.joined_room": LegJoinedRoomEvent,
    "leg.left_room": LegLeftRoomEvent,
    "leg.muted": LegMutedEvent,
    "leg.unmuted": LegUnmutedEvent,
    "leg.deaf": LegDeafEvent,
    "leg.undeaf": LegUndeafEvent,
    "leg.hold": LegHoldEvent,
    "leg.unhold": LegUnholdEvent,
    "leg.command_failed": LegCommandFailedEvent,
    "leg.stream_added": LegStreamAddedEvent,
    "leg.stream_removed": LegStreamRemovedEvent,
    "leg.stream_rejected": LegStreamRejectedEvent,
    "leg.stream_failed": LegStreamFailedEvent,
    "leg.stream_room_changed": LegStreamRoomChangedEvent,
    "leg.stream_role_changed": LegStreamRoleChangedEvent,
    "siprec.session_started": SIPRECSessionStartedEvent,
    "siprec.session_ended": SIPRECSessionEndedEvent,
    "siprec.metadata_updated": SIPRECMetadataUpdatedEvent,
    "siprec.participant_joined": SIPRECParticipantJoinedEvent,
    "siprec.participant_left": SIPRECParticipantLeftEvent,
    "dtmf.received": DTMFReceivedEvent,
    "rtt.received": RTTReceivedEvent,
    "speaking.started": SpeakingStartedEvent,
    "speaking.stopped": SpeakingStoppedEvent,
    "playback.started": PlaybackStartedEvent,
    "playback.finished": PlaybackFinishedEvent,
    "playback.error": PlaybackErrorEvent,
    "tts.started": TTSStartedEvent,
    "tts.finished": TTSFinishedEvent,
    "tts.error": TTSErrorEvent,
    "tts.staged": TTSStagedEvent,
    "tts.discarded": TTSDiscardedEvent,
    "recording.started": RecordingStartedEvent,
    "recording.finished": RecordingFinishedEvent,
    "recording.paused": RecordingPausedEvent,
    "recording.resumed": RecordingResumedEvent,
    "leg.transfer_initiated": LegTransferInitiatedEvent,
    "leg.transfer_requested": LegTransferRequestedEvent,
    "leg.transfer_progress": LegTransferProgressEvent,
    "leg.transfer_completed": LegTransferCompletedEvent,
    "leg.transfer_failed": LegTransferFailedEvent,
    "room.created": RoomCreatedEvent,
    "room.deleted": RoomDeletedEvent,
    "room.bridged": RoomBridgedEvent,
    "room.bridge_updated": RoomBridgeUpdatedEvent,
    "room.unbridged": RoomUnbridgedEvent,
    "room.routing_changed": RoomRoutingChangedEvent,
    "leg.role_changed": LegRoleChangedEvent,
    "stt.text": STTTextEvent,
    "stt.turn": STTTurnEvent,
    "agent.connected": AgentConnectedEvent,
    "agent.disconnected": AgentDisconnectedEvent,
    "agent.user_transcript": AgentUserTranscriptEvent,
    "agent.agent_response": AgentAgentResponseEvent,
    "amd.result": AMDResultEvent,
    "amd.beep": AMDBeepEvent,
    "sip.registration_attempt": SIPRegistrationAttemptEvent,
    "sip.registration_active": SIPRegistrationActiveEvent,
    "sip.registration_expired": SIPRegistrationExpiredEvent,
    "sip.outbound_registration_active": SIPOutboundRegistrationActiveEvent,
    "sip.outbound_registration_failed": SIPOutboundRegistrationFailedEvent,
    "sip.outbound_registration_expired": SIPOutboundRegistrationExpiredEvent,
}


def parse_event(data: bytes | str | dict[str, Any]) -> Event:
    """Decode a webhook / VSI event frame into its typed :class:`Event` subclass.

    Unknown event types fall back to the base :class:`Event`.
    """
    if isinstance(data, (bytes, str)):
        obj = json.loads(data)
    else:
        obj = data
    type_str = obj.get("type", "") if isinstance(obj, dict) else ""
    cls = _EVENT_TYPES.get(type_str, Event)
    return cls.model_validate(obj)
