"""GENERATED by tools/generate.py from VoiceBlender openapi.yaml + asyncapi.yaml.

DO NOT EDIT — run ``make generate`` to regenerate.
"""

from __future__ import annotations

import json
from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from voiceblender._models import ChannelInfo, OfferedCodec


class Event(BaseModel):
    """Base envelope for all webhook / VSI events."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    type: str
    timestamp: datetime
    instance_id: str | None = None


class LegRingingEvent(Event):
    """Fired when: sIP call ringing (inbound or outbound)"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None
    # Leg type (e.g. sip_inbound, sip_outbound)
    leg_type: str | None = None
    # Dialed SIP URI (outbound only)
    uri: str | None = None
    # Caller URI (inbound) or From header value (outbound, if set)
    from_: str | None = Field(default=None, alias="from")
    # Callee URI (inbound only)
    to: str | None = None
    # X-* custom SIP headers, if present
    sip_headers: dict[str, str] | None = None
    offered_codecs: list[OfferedCodec] | None = None


class LegEarlyMediaEvent(Event):
    """Fired when: outbound leg received 183 Session Progress with SDP; media pipeline active"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None
    # Leg type (e.g. sip_outbound)
    leg_type: str | None = None


class LegConnectedEvent(Event):
    """Fired when: leg answered/connected"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None
    # Leg type (e.g. sip_inbound, sip_outbound, webrtc)
    leg_type: str | None = None


class LegDisconnectedEventCdr(BaseModel):
    """LegDisconnectedEventCdr."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Disconnect reason. Common SIP failures are mapped to named reasons; unmapped 4xx/5xx/6xx codes appear as sip_{code}.
    reason: str
    # Seconds from leg creation to disconnect
    duration_total: float
    # Seconds from answer to disconnect (0 if never answered)
    duration_answered: float


class LegDisconnectedEventQuality(BaseModel):
    """RTP quality metrics. Omitted for WebRTC legs or unanswered legs with no media."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Mean Opinion Score (1.0–5.0) estimated via simplified E-model (ITU-T G.107) from packet loss and jitter
    mos_score: float
    # Total inbound RTP audio packets received
    rtp_packets_received: int
    # Estimated lost packets based on sequence number gaps
    rtp_packets_lost: int
    # Inter-arrival jitter in milliseconds (RFC 3550 §A.8)
    rtp_jitter_ms: float


class LegDisconnectedEvent(Event):
    """Fired when: leg hung up (CDR-style nested structure)"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None
    cdr: LegDisconnectedEventCdr | None = None
    # RTP quality metrics. Omitted for WebRTC legs or unanswered legs with no media.
    quality: LegDisconnectedEventQuality | None = None


class LegJoinedRoomEvent(Event):
    """Fired when: leg added to a room"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None


class LegLeftRoomEvent(Event):
    """Fired when: leg removed from a room"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None


class LegMutedEvent(Event):
    """Fired when: leg muted"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None


class LegUnmutedEvent(Event):
    """Fired when: leg unmuted"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None


class LegDeafEvent(Event):
    """Fired when: leg deafened (stops receiving room audio)"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    leg_id: str | None = None
    app_id: str | None = None


class LegUndeafEvent(Event):
    """Fired when: leg undeafened (resumes receiving room audio)"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    leg_id: str | None = None
    app_id: str | None = None


class LegHoldEvent(Event):
    """Fired when: leg put on hold (local or remote)"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None
    # Hold direction: "local" (we put them on hold) or "remote" (they put us on hold)
    leg_type: str | None = None


class LegUnholdEvent(Event):
    """Fired when: leg taken off hold (local or remote)"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None
    # Hold direction: "local" or "remote"
    leg_type: str | None = None


class LegCommandFailedEvent(Event):
    """Fired when: an asynchronous leg command (202 Accepted) failed during execution"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    leg_id: str | None = None
    app_id: str | None = None
    command: str | None = None
    error: str | None = None


class DTMFReceivedEvent(Event):
    """Fired when: dTMF digit received"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None
    # DTMF digit received
    digit: str | None = None
    seq: int | None = None


class RTTReceivedEvent(Event):
    """Fired when: real-Time Text (T.140 / RFC 4103) chunk received from the remote"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None
    # UTF-8 text chunk received from the remote
    text: str | None = None
    # Per-leg monotonic sequence (independent of RTP sequence numbers)
    seq: int | None = None
    # True when a U+FFFD has been prepended to indicate text was lost beyond what RFC 2198 redundancy could recover
    loss_marker: bool | None = None


class SpeakingStartedEvent(Event):
    """Fired when: participant started speaking"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier (present only when the leg is in a room)
    room_id: str | None = None
    app_id: str | None = None


class SpeakingStoppedEvent(Event):
    """Fired when: participant stopped speaking"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier (present only when the leg is in a room)
    room_id: str | None = None
    app_id: str | None = None


class PlaybackStartedEvent(Event):
    """Fired when: playback began"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None
    # Playback identifier
    playback_id: str | None = None


class PlaybackFinishedEvent(Event):
    """Fired when: playback ended"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None
    # Playback identifier
    playback_id: str | None = None


class PlaybackErrorEvent(Event):
    """Fired when: playback failed"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None
    # Playback identifier
    playback_id: str | None = None
    # Error message
    error: str | None = None


class TTSStartedEvent(Event):
    """Fired when: tTS synthesis began playing"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None
    # TTS playback identifier
    tts_id: str | None = None


class TTSFinishedEvent(Event):
    """Fired when: tTS synthesis finished playing"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None
    # TTS playback identifier
    tts_id: str | None = None


class TTSErrorEvent(Event):
    """Fired when: tTS synthesis or playback failed"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None
    # TTS playback identifier
    tts_id: str | None = None
    # Error message
    error: str | None = None


class RecordingStartedEvent(Event):
    """Fired when: recording began"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None
    # Recording file path or S3 URI
    file: str | None = None


class RecordingFinishedEvent(Event):
    """Fired when: recording ended"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None
    # Recording file path or S3 URI
    file: str | None = None
    multi_channel_file: str | None = None
    channels: dict[str, ChannelInfo] | None = None


class RecordingPausedEvent(Event):
    """Fired when: recording paused (audio replaced with silence)"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None
    file: str | None = None


class RecordingResumedEvent(Event):
    """Fired when: recording resumed from a paused state"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None
    file: str | None = None


class LegTransferInitiatedEvent(Event):
    """Fired when: we sent a SIP REFER (transfer initiated by the operator)"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None
    # Transfer kind: "blind" or "attended"
    kind: str | None = None
    # SIP URI to which the leg is being transferred
    target: str | None = None
    # Leg whose dialog is replaced (attended transfer only)
    replaces_leg_id: str | None = None


class LegTransferRequestedEvent(Event):
    """Fired when: we received a SIP REFER from the peer"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None
    # Transfer kind: "blind" or "attended"
    kind: str | None = None
    # SIP URI requested by the peer
    target: str | None = None
    # Call-ID present in the Refer-To Replaces parameter (attended only)
    replaces_call_id: str | None = None
    # True when the REFER was declined (e.g. SIP_REFER_AUTO_DIAL=false)
    declined: bool | None = None


class LegTransferProgressEvent(Event):
    """Fired when: transfer progress reported via NOTIFY sipfrag"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None
    # Provisional SIP status from the NOTIFY sipfrag
    status_code: int | None = None
    # Reason phrase
    reason: str | None = None


class LegTransferCompletedEvent(Event):
    """Fired when: transfer reached terminal 2xx"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None
    # Final 2xx SIP status from the NOTIFY sipfrag
    status_code: int | None = None
    # Reason phrase
    reason: str | None = None


class LegTransferFailedEvent(Event):
    """Fired when: transfer failed (REFER rejected, sipfrag non-2xx, or local error)"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None
    # Final non-2xx SIP status (when applicable)
    status_code: int | None = None
    # Reason phrase
    reason: str | None = None
    # Local error message (when no SIP status applies)
    error: str | None = None


class RoomCreatedEvent(Event):
    """Fired when: room created"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Room identifier
    room_id: str | None = None
    app_id: str | None = None


class RoomDeletedEvent(Event):
    """Fired when: room deleted"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Room identifier
    room_id: str | None = None
    app_id: str | None = None


class RoomBridgedEvent(Event):
    """Fired when: two rooms' mixers were joined"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Bridge identifier
    bridge_id: str | None = None
    # First bridged room
    room_a_id: str | None = None
    # Second bridged room
    room_b_id: str | None = None
    app_id: str | None = None
    # Canonical direction relative to room_a_id: "bidirectional", "a_to_b", "b_to_a", or "none"
    direction: str | None = None


class RoomBridgeUpdatedEvent(Event):
    """Fired when: a bridge's audio flow direction changed"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Bridge identifier
    bridge_id: str | None = None
    # First bridged room
    room_a_id: str | None = None
    # Second bridged room
    room_b_id: str | None = None
    app_id: str | None = None
    # New canonical direction relative to room_a_id
    direction: str | None = None


class RoomUnbridgedEvent(Event):
    """Fired when: a bridge was torn down"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Bridge identifier
    bridge_id: str | None = None
    # First bridged room
    room_a_id: str | None = None
    # Second bridged room
    room_b_id: str | None = None
    app_id: str | None = None
    # Empty for an explicit delete, or "room_deleted" when a bridged room was deleted
    reason: str | None = None


class STTTextEvent(Event):
    """Fired when: speech-to-text transcript"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None
    # Transcribed text
    text: str | None = None
    # Whether this is a final or partial transcript
    is_final: bool | None = None


class AgentConnectedEvent(Event):
    """Fired when: agent connected to provider"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None
    # Provider-assigned conversation identifier
    conversation_id: str | None = None


class AgentDisconnectedEvent(Event):
    """Fired when: agent session ended"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None


class AgentUserTranscriptEvent(Event):
    """Fired when: user speech transcribed by agent"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None
    # User speech text
    text: str | None = None


class AgentAgentResponseEvent(Event):
    """Fired when: agent generated a response"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    # Room identifier
    room_id: str | None = None
    app_id: str | None = None
    # Agent response text
    text: str | None = None


class AMDResultEvent(Event):
    """Fired when: answering machine detection completed"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None
    # Detection result: human, machine, no_speech, or not_sure
    result: str | None = None
    # Milliseconds of silence before first speech
    initial_silence_ms: int | None = None
    # Milliseconds of speech in the greeting
    greeting_duration_ms: int | None = None
    # Total milliseconds of analysis before determination
    total_analysis_ms: int | None = None


class AMDBeepEvent(Event):
    """Fired when: voicemail beep tone detected after machine classification"""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg identifier
    leg_id: str | None = None
    app_id: str | None = None
    # Milliseconds from machine detection to beep tone detection
    beep_ms: int | None = None


_EVENT_TYPES: dict[str, type[Event]] = {
    "leg.ringing": LegRingingEvent,
    "leg.early_media": LegEarlyMediaEvent,
    "leg.connected": LegConnectedEvent,
    "leg.disconnected": LegDisconnectedEvent,
    "leg.joined_room": LegJoinedRoomEvent,
    "leg.left_room": LegLeftRoomEvent,
    "leg.muted": LegMutedEvent,
    "leg.unmuted": LegUnmutedEvent,
    "leg.deaf": LegDeafEvent,
    "leg.undeaf": LegUndeafEvent,
    "leg.hold": LegHoldEvent,
    "leg.unhold": LegUnholdEvent,
    "leg.command_failed": LegCommandFailedEvent,
    "dtmf.received": DTMFReceivedEvent,
    "rtt.received": RTTReceivedEvent,
    "speaking.started": SpeakingStartedEvent,
    "speaking.stopped": SpeakingStoppedEvent,
    "playback.started": PlaybackStartedEvent,
    "playback.finished": PlaybackFinishedEvent,
    "playback.error": PlaybackErrorEvent,
    "tts.started": TTSStartedEvent,
    "tts.finished": TTSFinishedEvent,
    "tts.error": TTSErrorEvent,
    "recording.started": RecordingStartedEvent,
    "recording.finished": RecordingFinishedEvent,
    "recording.paused": RecordingPausedEvent,
    "recording.resumed": RecordingResumedEvent,
    "leg.transfer_initiated": LegTransferInitiatedEvent,
    "leg.transfer_requested": LegTransferRequestedEvent,
    "leg.transfer_progress": LegTransferProgressEvent,
    "leg.transfer_completed": LegTransferCompletedEvent,
    "leg.transfer_failed": LegTransferFailedEvent,
    "room.created": RoomCreatedEvent,
    "room.deleted": RoomDeletedEvent,
    "room.bridged": RoomBridgedEvent,
    "room.bridge_updated": RoomBridgeUpdatedEvent,
    "room.unbridged": RoomUnbridgedEvent,
    "stt.text": STTTextEvent,
    "agent.connected": AgentConnectedEvent,
    "agent.disconnected": AgentDisconnectedEvent,
    "agent.user_transcript": AgentUserTranscriptEvent,
    "agent.agent_response": AgentAgentResponseEvent,
    "amd.result": AMDResultEvent,
    "amd.beep": AMDBeepEvent,
}


def parse_event(data: bytes | str | dict[str, Any]) -> Event:
    """Decode a webhook / VSI event frame into its typed :class:`Event` subclass.

    Unknown event types fall back to the base :class:`Event`.
    """
    if isinstance(data, (bytes, str)):
        obj = json.loads(data)
    else:
        obj = data
    type_str = obj.get("type", "") if isinstance(obj, dict) else ""
    cls = _EVENT_TYPES.get(type_str, Event)
    return cls.model_validate(obj)
