"""GENERATED by tools/generate.py from VoiceBlender openapi.yaml + asyncapi.yaml.

DO NOT EDIT — run ``make generate`` to regenerate.
"""

from __future__ import annotations

from voiceblender._client import Client
from voiceblender._models import Leg, Room
from voiceblender._playback import PlaybackRequest
from voiceblender._requests import (
    AgentMessageRequest,
    AMDParams,
    AnswerLegRequest,
    CreateLegRequest,
    DeepgramAgentRequest,
    DeleteLegRequest,
    DTMFRequest,
    EarlyMediaLegRequest,
    ElevenLabsAgentRequest,
    PipecatAgentRequest,
    RecordingRequest,
    RTTRequest,
    STTRequest,
    TransferRequest,
    TTSRequest,
    VAPIAgentRequest,
    VolumeRequest,
)
from voiceblender._responses import StatusResponse
from voiceblender._responses_extra import PlaybackResponse, RecordingResponse, TTSResponse

__all__: list[str] = []

# Legs operations — bound onto Client / Leg / Room by class assignment.


async def _client_list_legs(self: Client) -> list[Leg]:
    """List all active legs"""
    return await self._do_list("GET", "/legs", item_model=Leg)


Client.list_legs = _client_list_legs  # type: ignore[method-assign]


async def _client_create_leg(self: Client, req: CreateLegRequest) -> Leg:
    """Originate an outbound leg

    Originate a new outbound leg. The `type` field selects the transport: `sip` originates a SIP INVITE; `whatsapp` originates a WhatsApp call through Meta; `websocket` dials a remote WebSocket endpoint (audio is PCM in either binary or `json_base64` framing, with bidirectional text and caller-supplied X-/P- headers).
    """
    out = await self._do("POST", "/legs", body=req, out_model=Leg)
    if out is not None:
        out._client = self
    assert out is not None, "createLeg" + ": empty response"
    return out


Client.create_leg = _client_create_leg  # type: ignore[method-assign]


async def _client_get_leg(self: Client, id: str) -> Leg:
    """Get a single leg"""
    out = await self._do("GET", f"/legs/{id}", out_model=Leg)
    if out is not None:
        out._client = self
    assert out is not None, "getLeg" + ": empty response"
    return out


Client.get_leg = _client_get_leg  # type: ignore[method-assign]


async def _leg_hangup(self: Leg, req: DeleteLegRequest) -> StatusResponse:
    """Hang up a leg (asynchronous)

    Validates the leg exists and queues a hangup. The HTTP call returns 202 as soon as the leg is found; the SIP work and cleanup run in the background, and the eventual disconnection is observed via the `leg.disconnected` event.

    Without a request body the legacy behavior is preserved: SIP BYE on connected legs (`cdr.reason: "api_hangup"`), or dialog cancel on unanswered inbound legs (`cdr.reason: "caller_cancel"`).

    With `{"reason": "<value>"}` and an unanswered SIP inbound leg (state `ringing` or `early_media`), VoiceBlender sends a final non-2xx response instead of BYE/cancel: `busy`→486, `declined`/`rejected`→603, `unavailable`→480, `not_found`→404, `forbidden`→403, `server_error`→500. The reason value is passed through to `leg.disconnected`'s `cdr.reason`.

    For connected legs the request body is ignored.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("DELETE", f"/legs/{self.id}", body=req, out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.hangup = _leg_hangup  # type: ignore[method-assign]


async def _leg_answer(self: Leg, req: AnswerLegRequest) -> StatusResponse:
    """Answer a ringing or early-media inbound SIP leg (asynchronous)

    Signals the inbound-call goroutine to send 200 OK. The HTTP call returns 202 immediately; the actual SIP 200 OK is sent in the background, and the leg's transition is observed via `leg.connected`. Pre-condition failures (wrong state, unknown codec) still return 4xx synchronously.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/legs/{self.id}/answer", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Leg.answer = _leg_answer  # type: ignore[method-assign]


async def _leg_ring(self: Leg) -> StatusResponse:
    """Send 180 Ringing on a ringing inbound SIP leg (asynchronous)

    Queues a SIP 180 Ringing provisional response with no SDP. Use when `SIP_AUTO_RINGING=false` (the default) and you want to indicate alerting before deciding to early-media or answer. Idempotent: each call emits another 180 — receivers tolerate re-sends. The HTTP call returns 202 as soon as the request is validated; SIP-level send failures surface as `leg.command_failed` with `command="ring"`.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("POST", f"/legs/{self.id}/ring", out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.ring = _leg_ring  # type: ignore[method-assign]


async def _leg_early_media(self: Leg, req: EarlyMediaLegRequest) -> StatusResponse:
    """Enable early media on a ringing inbound SIP leg (asynchronous)

    Queues a SIP 183 Session Progress with SDP and the RTP/codec setup. The HTTP call returns 202 as soon as the request is validated; the leg transitions to `early_media` state asynchronously, observable via `leg.early_media`. Setup failures surface as `leg.command_failed` with `command="early_media"`.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/legs/{self.id}/early-media", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Leg.early_media = _leg_early_media  # type: ignore[method-assign]


async def _leg_mute(self: Leg) -> StatusResponse:
    """Mute a leg

    A muted leg's audio is excluded from the room mix and speaking events are suppressed. Taps (recording/STT) still receive the muted leg's own audio.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("POST", f"/legs/{self.id}/mute", out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.mute = _leg_mute  # type: ignore[method-assign]


async def _leg_unmute(self: Leg) -> StatusResponse:
    """Unmute a leg"""
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("DELETE", f"/legs/{self.id}/mute", out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.unmute = _leg_unmute  # type: ignore[method-assign]


async def _leg_hold(self: Leg) -> StatusResponse:
    """Put a SIP call on hold (asynchronous)

    Queues a re-INVITE with `sendonly` SDP direction. The HTTP call returns 202 as soon as the leg is validated; the re-INVITE is sent in the background and success surfaces as `leg.hold`. Failures surface as `leg.command_failed` with `command="hold"`. The RTP timeout is paused while held, and a 2-hour auto-hangup timer starts.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("POST", f"/legs/{self.id}/hold", out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.hold = _leg_hold  # type: ignore[method-assign]


async def _leg_unhold(self: Leg) -> StatusResponse:
    """Resume a held SIP call (asynchronous)

    Queues a re-INVITE with `sendrecv` SDP direction. The HTTP call returns 202; success surfaces as `leg.unhold`, failures as `leg.command_failed` with `command="unhold"`.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("DELETE", f"/legs/{self.id}/hold", out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.unhold = _leg_unhold  # type: ignore[method-assign]


async def _leg_transfer(self: Leg, req: TransferRequest) -> StatusResponse:
    """Transfer a SIP leg via REFER (asynchronous)

    Asynchronously transfers a SIP leg. The HTTP call returns 202 as soon as the request is validated; the REFER is sent in the background and its outcome is surfaced through `leg.transfer_initiated` / `leg.transfer_progress` / `leg.transfer_completed` / `leg.transfer_failed` events. Blind transfer when `replaces_leg_id` is omitted; attended transfer when present (the named leg's dialog identity is embedded as a Replaces parameter per RFC 3891). On terminal 2xx the leg (and the replaces leg, if any) is hung up automatically.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/legs/{self.id}/transfer", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Leg.transfer = _leg_transfer  # type: ignore[method-assign]


async def _leg_send_dtmf(self: Leg, req: DTMFRequest) -> StatusResponse:
    """Send DTMF digits on a leg"""
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/legs/{self.id}/dtmf", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Leg.send_dtmf = _leg_send_dtmf  # type: ignore[method-assign]


async def _leg_enable_dtmf(self: Leg) -> StatusResponse:
    """Enable DTMF reception on a leg

    Allow this leg to receive DTMF digits broadcast from other legs in the same room. This is the default state for new legs.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("POST", f"/legs/{self.id}/dtmf/accept", out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.enable_dtmf = _leg_enable_dtmf  # type: ignore[method-assign]


async def _leg_disable_dtmf(self: Leg) -> StatusResponse:
    """Disable DTMF reception on a leg

    Block this leg from receiving DTMF digits broadcast from other legs in the same room. DTMF received from this leg's own far end is still emitted as a leg.dtmf event.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("POST", f"/legs/{self.id}/dtmf/reject", out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.disable_dtmf = _leg_disable_dtmf  # type: ignore[method-assign]


async def _leg_send_rtt(self: Leg, req: RTTRequest) -> StatusResponse:
    """Send Real-Time Text (T.140) on a SIP leg

    Sends UTF-8 text on the leg's RTT (T.140 / RFC 4103) media stream. Requires that the SDP offer/answer agreed on an m=text section with the remote UA. Enable RTT on the server with RTT_ENABLED=true.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("POST", f"/legs/{self.id}/rtt", body=req, out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.send_rtt = _leg_send_rtt  # type: ignore[method-assign]


async def _leg_accept_rtt_leg(self: Leg) -> StatusResponse:
    """Enable RTT reception on a leg

    Allow this leg to receive RTT text broadcast from other legs in the same room and to emit rtt.received events for incoming text. Default state for new legs.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("POST", f"/legs/{self.id}/rtt/accept", out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.accept_rtt_leg = _leg_accept_rtt_leg  # type: ignore[method-assign]


async def _leg_reject_rtt_leg(self: Leg) -> StatusResponse:
    """Disable RTT reception on a leg

    Block this leg from receiving RTT text broadcast from other legs in the same room and suppress rtt.received events for this leg.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("POST", f"/legs/{self.id}/rtt/reject", out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.reject_rtt_leg = _leg_reject_rtt_leg  # type: ignore[method-assign]


async def _leg_play(self: Leg, req: PlaybackRequest) -> PlaybackResponse:
    """Start audio playback to a leg"""
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/legs/{self.id}/play", body=req, out_model=PlaybackResponse
    )
    assert out is not None, "playLeg" + ": empty response"
    return out


Leg.play = _leg_play  # type: ignore[method-assign]


async def _leg_volume_play(self: Leg, playback_id: str, req: VolumeRequest) -> StatusResponse:
    """Change the volume of an active leg playback"""
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "PATCH", f"/legs/{self.id}/play/{playback_id}", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Leg.volume_play = _leg_volume_play  # type: ignore[method-assign]


async def _leg_stop_play(self: Leg, playback_id: str) -> StatusResponse:
    """Stop audio playback on a leg"""
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "DELETE", f"/legs/{self.id}/play/{playback_id}", out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Leg.stop_play = _leg_stop_play  # type: ignore[method-assign]


async def _leg_play_tts(self: Leg, req: TTSRequest) -> TTSResponse:
    """Synthesize speech and play it on a leg

    Synthesizes the provided text using the configured TTS provider and plays the audio on the leg. When `TTS_CACHE_ENABLED=true`, identical requests (same text, voice, model, language, and prompt) are stored on disk in `TTS_CACHE_DIR` and persist across restarts, without calling the external provider.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("POST", f"/legs/{self.id}/tts", body=req, out_model=TTSResponse)
    assert out is not None, "ttsLeg" + ": empty response"
    return out


Leg.play_tts = _leg_play_tts  # type: ignore[method-assign]


async def _leg_record(self: Leg, req: RecordingRequest) -> RecordingResponse:
    """Start recording a leg to a WAV file

    For SIP legs, recording is stereo (left=incoming, right=outgoing). For legs in a room, stereo at 16kHz (left=participant audio, right=mixed-minus-self).
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/legs/{self.id}/record", body=req, out_model=RecordingResponse
    )
    assert out is not None, "recordLeg" + ": empty response"
    return out


Leg.record = _leg_record  # type: ignore[method-assign]


async def _leg_stop_record(self: Leg) -> RecordingResponse:
    """Stop recording a leg"""
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("DELETE", f"/legs/{self.id}/record", out_model=RecordingResponse)
    assert out is not None, "stopRecordLeg" + ": empty response"
    return out


Leg.stop_record = _leg_stop_record  # type: ignore[method-assign]


async def _leg_pause_record(self: Leg) -> StatusResponse:
    """Pause a leg recording

    Replaces incoming audio with silence on the active recording until `/record/resume` is called. The WAV's timeline is preserved (silent gap where audio was paused), so reviewers can see exactly when sensitive data was excluded. Idempotent: calling while already paused returns `status: already_paused`.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("POST", f"/legs/{self.id}/record/pause", out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.pause_record = _leg_pause_record  # type: ignore[method-assign]


async def _leg_resume_record(self: Leg) -> StatusResponse:
    """Resume a paused leg recording

    Resumes writing real audio after a prior `/record/pause`. Idempotent: calling while not paused returns `status: not_paused`.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("POST", f"/legs/{self.id}/record/resume", out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.resume_record = _leg_resume_record  # type: ignore[method-assign]


async def _leg_stt(self: Leg, req: STTRequest) -> StatusResponse:
    """Start real-time speech-to-text on a leg"""
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("POST", f"/legs/{self.id}/stt", body=req, out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.stt = _leg_stt  # type: ignore[method-assign]


async def _leg_stop_stt(self: Leg) -> StatusResponse:
    """Stop speech-to-text on a leg"""
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("DELETE", f"/legs/{self.id}/stt", out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.stop_stt = _leg_stop_stt  # type: ignore[method-assign]


async def _leg_elevenlabs_agent(self: Leg, req: ElevenLabsAgentRequest) -> StatusResponse:
    """Attach an ElevenLabs ConvAI agent to a leg

    Bridges audio bidirectionally with an ElevenLabs conversational AI agent. Standalone legs use direct audio; legs in a room use mixer taps.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/legs/{self.id}/agent/elevenlabs", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Leg.elevenlabs_agent = _leg_elevenlabs_agent  # type: ignore[method-assign]


async def _leg_vapi_agent(self: Leg, req: VAPIAgentRequest) -> StatusResponse:
    """Attach a VAPI agent to a leg

    Bridges audio bidirectionally with a VAPI conversational AI agent. Standalone legs use direct audio; legs in a room use mixer taps.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/legs/{self.id}/agent/vapi", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Leg.vapi_agent = _leg_vapi_agent  # type: ignore[method-assign]


async def _leg_pipecat_agent(self: Leg, req: PipecatAgentRequest) -> StatusResponse:
    """Attach a Pipecat bot to a leg

    Bridges audio bidirectionally with a self-hosted Pipecat bot via WebSocket. Standalone legs use direct audio; legs in a room use mixer taps.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/legs/{self.id}/agent/pipecat", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Leg.pipecat_agent = _leg_pipecat_agent  # type: ignore[method-assign]


async def _leg_deepgram_agent(self: Leg, req: DeepgramAgentRequest) -> StatusResponse:
    """Attach a Deepgram Voice Agent to a leg

    Bridges audio bidirectionally with a Deepgram Voice Agent. Standalone legs use direct audio; legs in a room use mixer taps.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/legs/{self.id}/agent/deepgram", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Leg.deepgram_agent = _leg_deepgram_agent  # type: ignore[method-assign]


async def _leg_agent_message(self: Leg, req: AgentMessageRequest) -> StatusResponse:
    """Inject a message into a running agent session on a leg

    Sends a context message or instruction to the running agent. Supported by Deepgram (InjectAgentMessage), Pipecat (TextFrame), and VAPI (control URL). Returns 501 for ElevenLabs.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/legs/{self.id}/agent/message", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Leg.agent_message = _leg_agent_message  # type: ignore[method-assign]


async def _leg_stop_agent(self: Leg) -> StatusResponse:
    """Detach the agent from a leg"""
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("DELETE", f"/legs/{self.id}/agent", out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.stop_agent = _leg_stop_agent  # type: ignore[method-assign]


async def _leg_start_amd(self: Leg, req: AMDParams) -> StatusResponse:
    """Start answering machine detection on a connected leg"""
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("POST", f"/legs/{self.id}/amd", body=req, out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.start_amd = _leg_start_amd  # type: ignore[method-assign]

_unused: tuple = (Leg, Room)
