"""GENERATED by tools/generate.py from VoiceBlender openapi.yaml + asyncapi.yaml.

DO NOT EDIT — run ``make generate`` to regenerate.
"""

from __future__ import annotations

from voiceblender._client import Client
from voiceblender._models import Leg, Room
from voiceblender._playback import PlaybackRequest
from voiceblender._requests import (
    AddLegStreamRequest,
    AgentMessageRequest,
    AMDParams,
    AnswerLegRequest,
    AttachStreamRoomRequest,
    ChallengeRequest,
    CreateLegRequest,
    DeepgramAgentRequest,
    DeleteLegRequest,
    DTMFRequest,
    EarlyMediaLegRequest,
    ElevenLabsAgentRequest,
    LegStreamView,
    PipecatAgentRequest,
    RecordingRequest,
    RTTRequest,
    SetLegRoleRequest,
    SIPRECSessionView,
    StartSIPRECRequest,
    STTRequest,
    TransferCompleteRequest,
    TransferDeclineRequest,
    TransferProgressRequest,
    TransferRequest,
    TTSRequest,
    UpdateLegStreamRequest,
    VAPIAgentRequest,
    VolumeRequest,
)
from voiceblender._responses import StatusResponse
from voiceblender._responses_extra import PlaybackResponse, RecordingResponse, TTSResponse

__all__: list[str] = []

# Legs operations — bound onto Client / Leg / Room by class assignment.


async def _client_list_legs(self: Client) -> list[Leg]:
    """List all active legs"""
    return await self._do_list("GET", "/legs", item_model=Leg)


Client.list_legs = _client_list_legs  # type: ignore[method-assign]


async def _client_create_leg(self: Client, req: CreateLegRequest) -> Leg:
    """Originate an outbound leg

    Originate a new outbound leg. The `type` field selects the transport: `sip` originates a SIP INVITE; `whatsapp` originates a WhatsApp call through Meta; `websocket` dials a remote WebSocket endpoint (audio is PCM in either binary or `json_base64` framing, with bidirectional text and caller-supplied X-/P- headers).
    """
    out = await self._do("POST", "/legs", body=req, out_model=Leg)
    if out is not None:
        out._client = self
    assert out is not None, "createLeg" + ": empty response"
    return out


Client.create_leg = _client_create_leg  # type: ignore[method-assign]


async def _client_moq_leg(self: Client) -> StatusResponse:
    """Connect a MoQ (Media over QUIC) leg (WebTransport extended-CONNECT, experimental)

    **Actual HTTP method: `CONNECT`** (HTTP/3 extended-CONNECT for WebTransport). OpenAPI 3.1 does not define `connect` as a path-item method, so this operation is documented under `post` with an `x-actual-method: CONNECT` extension. Standard HTTP clients (e.g. `curl -X POST`) will receive `405 Method Not Allowed` — use a WebTransport-capable HTTP/3 client.

    **Experimental / PoC.** Upgrades an HTTP/3 extended-CONNECT request to a WebTransport session and creates an inbound MoQ leg. Reachable only over HTTP/3 on the MoQ listener (not on the regular HTTP/1.1 chi listener). Requires `MOQ_ENABLED=true` plus `MOQ_TLS_CERT_FILE` and `MOQ_TLS_KEY_FILE`. Speaks IETF draft-11 of moq-transport (via `mengelbart/moqtransport`); browser interop with draft-16 clients (moqtail, moq.dev) is not expected to work. Media is bidirectional within a single MoQ session per leg: the server publishes namespace `mix`/track `audio` (downlink, room mix) and subscribes to namespace `mic`/track `audio` (uplink, leg mic). Audio is Opus framed one frame per MoQ Object (LOC-style) at 48 kHz mono, 20 ms frames. Query parameters: `sample_rate` (only `48000` is accepted — the encoder/decoder are hard-wired to 48 kHz; default 48000); `room_id` to auto-add the leg to a room; `app_id` for event filtering; `webhook_url`/`webhook_secret` for per-leg event routing. X-* and P-* request headers (plus Authorization) are captured into the leg's `headers` map and surfaced on `LegView`. The leg goes straight to `connected` (no ringing/answer flow); no DTMF, no RTT, and event parity is limited to `leg.connected` / `leg.disconnected`.
    """
    out = await self._do("POST", "/legs/moq", out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Client.moq_leg = _client_moq_leg  # type: ignore[method-assign]


async def _client_get_leg(self: Client, id: str) -> Leg:
    """Get a single leg"""
    out = await self._do("GET", f"/legs/{id}", out_model=Leg)
    if out is not None:
        out._client = self
    assert out is not None, "getLeg" + ": empty response"
    return out


Client.get_leg = _client_get_leg  # type: ignore[method-assign]


async def _leg_hangup(self: Leg, req: DeleteLegRequest) -> StatusResponse:
    """Hang up a leg (asynchronous)

    Validates the leg exists and queues a hangup. The HTTP call returns 202 as soon as the leg is found; the SIP work and cleanup run in the background, and the eventual disconnection is observed via the `leg.disconnected` event.

    Without a request body the legacy behavior is preserved: SIP BYE on connected legs (`cdr.reason: "api_hangup"`), or dialog cancel on unanswered inbound legs (`cdr.reason: "caller_cancel"`).

    With `{"reason": "<value>"}` and an unanswered SIP inbound leg (state `ringing` or `early_media`), VoiceBlender sends a final non-2xx response instead of BYE/cancel: `busy`→486, `declined`/`rejected`→603, `unavailable`→480, `not_found`→404, `forbidden`→403, `server_error`→500. The reason value is passed through to `leg.disconnected`'s `cdr.reason`.

    For connected legs the request body is ignored.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("DELETE", f"/legs/{self.id}", body=req, out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.hangup = _leg_hangup  # type: ignore[method-assign]


async def _leg_answer(self: Leg, req: AnswerLegRequest) -> StatusResponse:
    """Answer a ringing or early-media inbound SIP leg (asynchronous)

    Signals the inbound-call goroutine to send 200 OK. The HTTP call returns 202 immediately; the actual SIP 200 OK is sent in the background, and the leg's transition is observed via `leg.connected`. Pre-condition failures (wrong state, unknown codec) still return 4xx synchronously. When the caller offers several m=audio sections they are all accepted; `streams` optionally routes each accepted stream beyond the primary into its own room, applied once the answer is negotiated.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/legs/{self.id}/answer", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Leg.answer = _leg_answer  # type: ignore[method-assign]


async def _leg_ring(self: Leg) -> StatusResponse:
    """Send 180 Ringing on a ringing inbound SIP leg (asynchronous)

    Queues a SIP 180 Ringing provisional response with no SDP. Use when `SIP_AUTO_RINGING=false` (the default) and you want to indicate alerting before deciding to early-media or answer. Idempotent: each call emits another 180 — receivers tolerate re-sends. The HTTP call returns 202 as soon as the request is validated; SIP-level send failures surface as `leg.command_failed` with `command="ring"`.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("POST", f"/legs/{self.id}/ring", out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.ring = _leg_ring  # type: ignore[method-assign]


async def _leg_challenge_leg(self: Leg, req: ChallengeRequest) -> StatusResponse:
    """Challenge a ringing inbound SIP leg with a 401 digest auth request

    Sends a SIP 401 Unauthorized carrying a `WWW-Authenticate` digest challenge on an unanswered inbound INVITE. The current leg is torn down (a `leg.disconnected` with `reason="challenged"` is published); the UAC's credentialed re-INVITE arrives as a new inbound call surfaced via `leg.ringing` with `authenticated=true` once VoiceBlender verifies the response against the supplied credential. Provide either `password` or `ha1`. An invalid retry is answered with 403 Forbidden and never surfaced.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/legs/{self.id}/challenge", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Leg.challenge_leg = _leg_challenge_leg  # type: ignore[method-assign]


async def _leg_early_media(self: Leg, req: EarlyMediaLegRequest) -> StatusResponse:
    """Enable early media on a ringing inbound SIP leg (asynchronous)

    Queues a SIP 183 Session Progress with SDP and the RTP/codec setup. The HTTP call returns 202 as soon as the request is validated; the leg transitions to `early_media` state asynchronously, observable via `leg.early_media`. Setup failures surface as `leg.command_failed` with `command="early_media"`.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/legs/{self.id}/early-media", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Leg.early_media = _leg_early_media  # type: ignore[method-assign]


async def _leg_mute(self: Leg) -> StatusResponse:
    """Mute a leg

    A muted leg's audio is excluded from the room mix and speaking events are suppressed. Taps (recording/STT) still receive the muted leg's own audio.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("POST", f"/legs/{self.id}/mute", out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.mute = _leg_mute  # type: ignore[method-assign]


async def _leg_unmute(self: Leg) -> StatusResponse:
    """Unmute a leg"""
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("DELETE", f"/legs/{self.id}/mute", out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.unmute = _leg_unmute  # type: ignore[method-assign]


async def _leg_hold(self: Leg) -> StatusResponse:
    """Put a SIP call on hold (asynchronous)

    Queues a re-INVITE with `sendonly` SDP direction. The HTTP call returns 202 as soon as the leg is validated; the re-INVITE is sent in the background and success surfaces as `leg.hold`. Failures surface as `leg.command_failed` with `command="hold"`. The RTP timeout is paused while held, and a 2-hour auto-hangup timer starts.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("POST", f"/legs/{self.id}/hold", out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.hold = _leg_hold  # type: ignore[method-assign]


async def _leg_unhold(self: Leg) -> StatusResponse:
    """Resume a held SIP call (asynchronous)

    Queues a re-INVITE with `sendrecv` SDP direction. The HTTP call returns 202; success surfaces as `leg.unhold`, failures as `leg.command_failed` with `command="unhold"`.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("DELETE", f"/legs/{self.id}/hold", out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.unhold = _leg_unhold  # type: ignore[method-assign]


async def _leg_transfer(self: Leg, req: TransferRequest) -> StatusResponse:
    """Transfer a SIP leg via REFER (asynchronous)

    Asynchronously transfers a SIP leg. The HTTP call returns 202 as soon as the request is validated; the REFER is sent in the background and its outcome is surfaced through `leg.transfer_initiated` / `leg.transfer_progress` / `leg.transfer_completed` / `leg.transfer_failed` events. Blind transfer when `replaces_leg_id` is omitted; attended transfer when present (the named leg's dialog identity is embedded as a Replaces parameter per RFC 3891). On terminal 2xx the leg (and the replaces leg, if any) is hung up automatically.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/legs/{self.id}/transfer", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Leg.transfer = _leg_transfer  # type: ignore[method-assign]


async def _leg_accept_transfer(self: Leg) -> StatusResponse:
    """Accept a parked inbound REFER

    Accepts an inbound transfer surfaced via `leg.transfer_requested` (default app-driven model, `SIP_REFER_AUTO_DIAL=false`). Sends `202 Accepted` to the referrer and a `NOTIFY` sipfrag `100 Trying`, keeping the refer subscription open. `{id}` is the referrer leg (the leg that received the REFER). After accepting, re-bridge as needed and report progress via `.../transfer/progress` and the outcome via `.../transfer/complete`.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/legs/{self.id}/transfer/accept", out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Leg.accept_transfer = _leg_accept_transfer  # type: ignore[method-assign]


async def _leg_transfer_progress(self: Leg, req: TransferProgressRequest) -> StatusResponse:
    """Report interim transfer progress

    Sends an interim sipfrag `NOTIFY` (e.g. `180 Ringing`) on an accepted inbound transfer so the referrer's UA reflects real progress. The subscription stays active.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/legs/{self.id}/transfer/progress", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Leg.transfer_progress = _leg_transfer_progress  # type: ignore[method-assign]


async def _leg_complete_transfer(self: Leg, req: TransferCompleteRequest) -> StatusResponse:
    """Complete an accepted inbound transfer

    Terminates an accepted inbound transfer with a final sipfrag `NOTIFY` and emits `leg.transfer_completed` (on success) or `leg.transfer_failed`. `success:true` sends `200 OK`; otherwise `status_code`/`reason` (default 500) carry the failure. The referrer leg is left for the app to hang up.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/legs/{self.id}/transfer/complete", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Leg.complete_transfer = _leg_complete_transfer  # type: ignore[method-assign]


async def _leg_decline_transfer(self: Leg, req: TransferDeclineRequest) -> StatusResponse:
    """Decline a parked inbound REFER

    Rejects a parked (not-yet-accepted) inbound transfer, replying to the referrer with a non-2xx (`603 Decline` by default; override via `code`/`reason`) and emitting `leg.transfer_failed`.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/legs/{self.id}/transfer/decline", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Leg.decline_transfer = _leg_decline_transfer  # type: ignore[method-assign]


async def _leg_send_dtmf(self: Leg, req: DTMFRequest) -> StatusResponse:
    """Send DTMF digits on a leg"""
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/legs/{self.id}/dtmf", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Leg.send_dtmf = _leg_send_dtmf  # type: ignore[method-assign]


async def _leg_enable_dtmf(self: Leg) -> StatusResponse:
    """Enable DTMF reception on a leg

    Allow this leg to receive DTMF digits broadcast from other legs in the same room. This is the default state for new legs.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("POST", f"/legs/{self.id}/dtmf/accept", out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.enable_dtmf = _leg_enable_dtmf  # type: ignore[method-assign]


async def _leg_disable_dtmf(self: Leg) -> StatusResponse:
    """Disable DTMF reception on a leg

    Block this leg from receiving DTMF digits broadcast from other legs in the same room. DTMF received from this leg's own far end is still emitted as a leg.dtmf event.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("POST", f"/legs/{self.id}/dtmf/reject", out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.disable_dtmf = _leg_disable_dtmf  # type: ignore[method-assign]


async def _leg_send_rtt(self: Leg, req: RTTRequest) -> StatusResponse:
    """Send Real-Time Text (T.140) on a SIP leg

    Sends UTF-8 text on the leg's RTT (T.140 / RFC 4103) media stream. Requires that the SDP offer/answer agreed on an m=text section with the remote UA. Enable RTT on the server with RTT_ENABLED=true.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("POST", f"/legs/{self.id}/rtt", body=req, out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.send_rtt = _leg_send_rtt  # type: ignore[method-assign]


async def _leg_accept_rtt_leg(self: Leg) -> StatusResponse:
    """Enable RTT reception on a leg

    Allow this leg to receive RTT text broadcast from other legs in the same room and to emit rtt.received events for incoming text. Default state for new legs.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("POST", f"/legs/{self.id}/rtt/accept", out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.accept_rtt_leg = _leg_accept_rtt_leg  # type: ignore[method-assign]


async def _leg_reject_rtt_leg(self: Leg) -> StatusResponse:
    """Disable RTT reception on a leg

    Block this leg from receiving RTT text broadcast from other legs in the same room and suppress rtt.received events for this leg.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("POST", f"/legs/{self.id}/rtt/reject", out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.reject_rtt_leg = _leg_reject_rtt_leg  # type: ignore[method-assign]


async def _leg_play(self: Leg, req: PlaybackRequest) -> PlaybackResponse:
    """Start audio playback to a leg"""
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/legs/{self.id}/play", body=req, out_model=PlaybackResponse
    )
    assert out is not None, "playLeg" + ": empty response"
    return out


Leg.play = _leg_play  # type: ignore[method-assign]


async def _leg_volume_play(self: Leg, playback_id: str, req: VolumeRequest) -> StatusResponse:
    """Change the volume of an active leg playback"""
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "PATCH", f"/legs/{self.id}/play/{playback_id}", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Leg.volume_play = _leg_volume_play  # type: ignore[method-assign]


async def _leg_stop_play(self: Leg, playback_id: str) -> StatusResponse:
    """Stop audio playback on a leg"""
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "DELETE", f"/legs/{self.id}/play/{playback_id}", out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Leg.stop_play = _leg_stop_play  # type: ignore[method-assign]


async def _leg_play_tts(self: Leg, req: TTSRequest) -> TTSResponse:
    """Synthesize speech and play it on a leg

    Synthesizes the provided text using the configured TTS provider and plays the audio on the leg. When `TTS_CACHE_ENABLED=true`, identical requests (same text, voice, model, language, and prompt) are stored on disk in `TTS_CACHE_DIR` and persist across restarts, without calling the external provider.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("POST", f"/legs/{self.id}/tts", body=req, out_model=TTSResponse)
    assert out is not None, "ttsLeg" + ": empty response"
    return out


Leg.play_tts = _leg_play_tts  # type: ignore[method-assign]


async def _leg_preflight_tts_leg(self: Leg, req: TTSRequest) -> StatusResponse:
    """Synthesize speech and hold it for a later commit

    Stages a speculative reply. The audio is synthesized and buffered in memory but not played, so that committing it starts playback with no synthesis delay. Intended for the turn-taking loop of a voice agent: start a draft reply on the `eager_end_of_turn` `stt.turn` event, then commit it on `end_of_turn` or discard it on `turn_resumed`. A `tts.staged` event reports when the audio is ready; synthesis failures are reported on `tts.error`. Staged utterances are dropped after `TTS_PREFLIGHT_TTL` or when the leg ends, and at most `TTS_PREFLIGHT_MAX_PER_LEG` may be staged on one leg at a time. Preflight is leg-scoped; use `POST /rooms/{id}/tts` for room announcements.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/legs/{self.id}/tts/preflight", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Leg.preflight_tts_leg = _leg_preflight_tts_leg  # type: ignore[method-assign]


async def _leg_commit_tts_leg(self: Leg, tts_id: str) -> StatusResponse:
    """Play a staged TTS utterance

    Starts playback of an utterance staged by the preflight endpoint. Returns immediately, before synthesis has necessarily finished; failure is reported asynchronously on `tts.error`, exactly as for `POST /legs/{id}/tts`. Once committed, stop playback with `DELETE /legs/{id}/play/{playbackID}` using the same `tts_id`.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/legs/{self.id}/tts/{tts_id}/commit", out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Leg.commit_tts_leg = _leg_commit_tts_leg  # type: ignore[method-assign]


async def _leg_discard_tts_leg(self: Leg, tts_id: str) -> StatusResponse:
    """Drop a staged TTS utterance without playing it

    Discards an utterance staged by the preflight endpoint, aborting synthesis if it is still in flight. Already-committed utterances are stopped with `DELETE /legs/{id}/play/{playbackID}` instead.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "DELETE", f"/legs/{self.id}/tts/{tts_id}", out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Leg.discard_tts_leg = _leg_discard_tts_leg  # type: ignore[method-assign]


async def _leg_record(self: Leg, req: RecordingRequest) -> RecordingResponse:
    """Start recording a leg to a WAV file

    For SIP legs, recording is stereo (left=incoming, right=outgoing). For legs in a room, stereo at 16kHz (left=participant audio, right=mixed-minus-self).
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/legs/{self.id}/record", body=req, out_model=RecordingResponse
    )
    assert out is not None, "recordLeg" + ": empty response"
    return out


Leg.record = _leg_record  # type: ignore[method-assign]


async def _leg_stop_record(self: Leg) -> RecordingResponse:
    """Stop recording a leg"""
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("DELETE", f"/legs/{self.id}/record", out_model=RecordingResponse)
    assert out is not None, "stopRecordLeg" + ": empty response"
    return out


Leg.stop_record = _leg_stop_record  # type: ignore[method-assign]


async def _leg_pause_record(self: Leg) -> StatusResponse:
    """Pause a leg recording

    Replaces incoming audio with silence on the active recording until `/record/resume` is called. The WAV's timeline is preserved (silent gap where audio was paused), so reviewers can see exactly when sensitive data was excluded. Idempotent: calling while already paused returns `status: already_paused`.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("POST", f"/legs/{self.id}/record/pause", out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.pause_record = _leg_pause_record  # type: ignore[method-assign]


async def _leg_resume_record(self: Leg) -> StatusResponse:
    """Resume a paused leg recording

    Resumes writing real audio after a prior `/record/pause`. Idempotent: calling while not paused returns `status: not_paused`.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("POST", f"/legs/{self.id}/record/resume", out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.resume_record = _leg_resume_record  # type: ignore[method-assign]


async def _leg_stt(self: Leg, req: STTRequest) -> StatusResponse:
    """Start real-time speech-to-text on a leg"""
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("POST", f"/legs/{self.id}/stt", body=req, out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.stt = _leg_stt  # type: ignore[method-assign]


async def _leg_stop_stt(self: Leg) -> StatusResponse:
    """Stop speech-to-text on a leg"""
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("DELETE", f"/legs/{self.id}/stt", out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.stop_stt = _leg_stop_stt  # type: ignore[method-assign]


async def _leg_finalize_stt_leg(self: Leg) -> StatusResponse:
    """Flush the STT buffer on a leg without stopping STT

    Forces the provider to emit a final transcript for the audio buffered so far while the session keeps running, so a caller that knows the speaker has finished does not have to wait for the provider's own endpointing. Only the `deepgram` provider supports this; `deepgram_flux`, `azure` and `elevenlabs` answer 501 — /v2/listen has no flush message, and Flux reports turn ends itself on stt.turn. The flushed transcript arrives on the usual stt.text event with is_final true — a segment containing no speech produces no event at all, so do not block on one.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("POST", f"/legs/{self.id}/stt/finalize", out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.finalize_stt_leg = _leg_finalize_stt_leg  # type: ignore[method-assign]


async def _leg_elevenlabs_agent(self: Leg, req: ElevenLabsAgentRequest) -> StatusResponse:
    """Attach an ElevenLabs ConvAI agent to a leg

    Bridges audio bidirectionally with an ElevenLabs conversational AI agent. Standalone legs use direct audio; legs in a room use mixer taps.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/legs/{self.id}/agent/elevenlabs", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Leg.elevenlabs_agent = _leg_elevenlabs_agent  # type: ignore[method-assign]


async def _leg_vapi_agent(self: Leg, req: VAPIAgentRequest) -> StatusResponse:
    """Attach a VAPI agent to a leg

    Bridges audio bidirectionally with a VAPI conversational AI agent. Standalone legs use direct audio; legs in a room use mixer taps.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/legs/{self.id}/agent/vapi", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Leg.vapi_agent = _leg_vapi_agent  # type: ignore[method-assign]


async def _leg_pipecat_agent(self: Leg, req: PipecatAgentRequest) -> StatusResponse:
    """Attach a Pipecat bot to a leg

    Bridges audio bidirectionally with a self-hosted Pipecat bot via WebSocket. Standalone legs use direct audio; legs in a room use mixer taps.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/legs/{self.id}/agent/pipecat", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Leg.pipecat_agent = _leg_pipecat_agent  # type: ignore[method-assign]


async def _leg_deepgram_agent(self: Leg, req: DeepgramAgentRequest) -> StatusResponse:
    """Attach a Deepgram Voice Agent to a leg

    Bridges audio bidirectionally with a Deepgram Voice Agent. Standalone legs use direct audio; legs in a room use mixer taps.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/legs/{self.id}/agent/deepgram", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Leg.deepgram_agent = _leg_deepgram_agent  # type: ignore[method-assign]


async def _leg_agent_message(self: Leg, req: AgentMessageRequest) -> StatusResponse:
    """Inject a message into a running agent session on a leg

    Sends a context message or instruction to the running agent. Supported by Deepgram (InjectAgentMessage), Pipecat (TextFrame), and VAPI (control URL). Returns 501 for ElevenLabs.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/legs/{self.id}/agent/message", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Leg.agent_message = _leg_agent_message  # type: ignore[method-assign]


async def _leg_stop_agent(self: Leg) -> StatusResponse:
    """Detach the agent from a leg"""
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("DELETE", f"/legs/{self.id}/agent", out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.stop_agent = _leg_stop_agent  # type: ignore[method-assign]


async def _leg_start_amd(self: Leg, req: AMDParams) -> StatusResponse:
    """Start answering machine detection on a connected leg"""
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("POST", f"/legs/{self.id}/amd", body=req, out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Leg.start_amd = _leg_start_amd  # type: ignore[method-assign]


async def _leg_get_siprec_session(self: Leg) -> SIPRECSessionView:
    """Get a SIPREC recording session

    Returns the RFC 7865 recording metadata of an inbound SIPREC session (leg type `siprec_in`): every recorded participant, every negotiated media stream, and the binding between them. A stream's `a=label` is what ties the m= section to a participant, so the `streams` entries carry both the leg stream ID and the participant identity. The raw metadata document is returned verbatim in `metadata`.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("GET", f"/legs/{self.id}/siprec", out_model=SIPRECSessionView)
    assert out is not None, "getSIPRECSession" + ": empty response"
    return out


Leg.get_siprec_session = _leg_get_siprec_session  # type: ignore[method-assign]


async def _leg_start_leg_siprec(self: Leg, req: StartSIPRECRequest) -> Leg:
    """Fork a single call to an external SIPREC recording server

    Originates a SIPREC recording session (RFC 7866) carrying one call as two `sendonly` sections: what the far end says, and what this server sends them. No room is involved. `leg_ids` is ignored here — the two sections are fixed. Returns the resulting `siprec_out` leg; delete it to end the session. Requires `SIPREC_SRC_ENABLED=true`.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("POST", f"/legs/{self.id}/siprec", body=req, out_model=Leg)
    if out is not None:
        out._client = self._client
    assert out is not None, "startLegSIPREC" + ": empty response"
    return out


Leg.start_leg_siprec = _leg_start_leg_siprec  # type: ignore[method-assign]


async def _leg_list_leg_streams(self: Leg) -> list[LegStreamView]:
    """List a leg's audio streams

    Returns every negotiated m=audio section on the leg, in m-line order. A single-stream call has exactly one entry, the primary.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    return await self._client._do_list("GET", f"/legs/{self.id}/streams", item_model=LegStreamView)


Leg.list_leg_streams = _leg_list_leg_streams  # type: ignore[method-assign]


async def _leg_add_leg_stream(self: Leg, req: AddLegStreamRequest) -> LegStreamView:
    """Add an audio stream to a live call

    Negotiates an additional m=audio section with a re-INVITE (RFC 3264 §8.1). The new section is appended below the existing ones and binds its own RTP port. Use it to carry a second independent audio stream — a translated feed, for example — alongside the original. Set `content` to "alt" and `lang` to the feed's language so the peer can tell them apart. A peer that answers the new section with port 0 leaves the call untouched and this returns 409.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/legs/{self.id}/streams", body=req, out_model=LegStreamView
    )
    assert out is not None, "addLegStream" + ": empty response"
    return out


Leg.add_leg_stream = _leg_add_leg_stream  # type: ignore[method-assign]


async def _leg_get_leg_stream(self: Leg, stream_id: str) -> LegStreamView:
    """Get one of a leg's audio streams"""
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "GET", f"/legs/{self.id}/streams/{stream_id}", out_model=LegStreamView
    )
    assert out is not None, "getLegStream" + ": empty response"
    return out


Leg.get_leg_stream = _leg_get_leg_stream  # type: ignore[method-assign]


async def _leg_update_leg_stream(
    self: Leg, stream_id: str, req: UpdateLegStreamRequest
) -> LegStreamView:
    """Change an audio stream's routing role

    Updates the stream's role in place and, when the stream is mixed into a room, recomputes that room's matrix-derived allow-sets atomically (single mixer-mutex acquisition), so no audio bleeds through mid-change. Emits `leg.stream_role_changed` and `room.routing_changed` with `reason: leg_stream_role_changed`.

    Only the role is mutable here. The SDP-level attributes — direction, lang, content, label — are fixed when the stream is negotiated; change them by removing the stream and adding a new one.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "PATCH", f"/legs/{self.id}/streams/{stream_id}", body=req, out_model=LegStreamView
    )
    assert out is not None, "updateLegStream" + ": empty response"
    return out


Leg.update_leg_stream = _leg_update_leg_stream  # type: ignore[method-assign]


async def _leg_remove_leg_stream(self: Leg, stream_id: str) -> StatusResponse:
    """Remove an audio stream from a live call

    Disables the stream with a re-INVITE carrying port 0 for its section (RFC 3264 §8.2) and releases its RTP port. The m-line slot survives as a tombstone — the m-line count never decreases for the life of a dialog — so a later added stream takes a new position. The primary stream carries the call and cannot be removed.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "DELETE", f"/legs/{self.id}/streams/{stream_id}", out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Leg.remove_leg_stream = _leg_remove_leg_stream  # type: ignore[method-assign]


async def _leg_attach_leg_stream_room(
    self: Leg, stream_id: str, req: AttachStreamRoomRequest
) -> LegStreamView:
    """Mix an audio stream into a room

    Attaches one of the leg's secondary streams to a room, which may differ from the leg's own room — that is what lets an original audio stream and a translated one be mixed separately. A leg never hears its own other streams, whatever the routing matrix says.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/legs/{self.id}/streams/{stream_id}/room", body=req, out_model=LegStreamView
    )
    assert out is not None, "attachLegStreamRoom" + ": empty response"
    return out


Leg.attach_leg_stream_room = _leg_attach_leg_stream_room  # type: ignore[method-assign]


async def _leg_detach_leg_stream_room(self: Leg, stream_id: str) -> LegStreamView:
    """Remove an audio stream from its room"""
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "DELETE", f"/legs/{self.id}/streams/{stream_id}/room", out_model=LegStreamView
    )
    assert out is not None, "detachLegStreamRoom" + ": empty response"
    return out


Leg.detach_leg_stream_room = _leg_detach_leg_stream_room  # type: ignore[method-assign]


async def _leg_set_role(self: Leg, req: SetLegRoleRequest) -> Leg:
    """Change a leg's routing role

    Updates the leg's routing role and, if the leg is currently in a room, recomputes the room's matrix-derived allow-sets atomically (single mixer-mutex acquisition). The next mix tick (≤ 20 ms) reflects the change.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("PATCH", f"/legs/{self.id}/role", body=req, out_model=Leg)
    if out is not None:
        out._client = self._client
    assert out is not None, "setLegRole" + ": empty response"
    return out


Leg.set_role = _leg_set_role  # type: ignore[method-assign]

_unused: tuple = (Leg, Room)
