"""GENERATED by tools/generate.py from VoiceBlender openapi.yaml + asyncapi.yaml.

DO NOT EDIT — run ``make generate`` to regenerate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, ConfigDict, PrivateAttr

if TYPE_CHECKING:
    from voiceblender._client import Client
from enum import Enum


class LegType(str, Enum):
    """Identifies the type of a voice leg."""

    SIP_INBOUND = "sip_inbound"
    SIP_OUTBOUND = "sip_outbound"
    WEBRTC = "webrtc"
    WHATSAPP_IN = "whatsapp_in"
    WHATSAPP_OUT = "whatsapp_out"
    WEBSOCKET_IN = "websocket_in"
    WEBSOCKET_OUT = "websocket_out"
    MOQ_IN = "moq_in"
    LIVEKIT_PUBLISH = "livekit_publish"
    LIVEKIT_PARTICIPANT = "livekit_participant"


class LegState(str, Enum):
    """The current state of a leg."""

    PENDING = "pending"
    RINGING = "ringing"
    EARLY_MEDIA = "early_media"
    CONNECTED = "connected"
    HELD = "held"
    HUNG_UP = "hung_up"


class WebhookEventType(str, Enum):
    """The type of a webhook event."""

    LEG_RINGING = "leg.ringing"
    LEG_EARLY_MEDIA = "leg.early_media"
    LEG_CONNECTED = "leg.connected"
    LEG_DISCONNECTED = "leg.disconnected"
    LEG_JOINED_ROOM = "leg.joined_room"
    LEG_LEFT_ROOM = "leg.left_room"
    LEG_MUTED = "leg.muted"
    LEG_UNMUTED = "leg.unmuted"
    LEG_DEAF = "leg.deaf"
    LEG_UNDEAF = "leg.undeaf"
    LEG_HOLD = "leg.hold"
    LEG_UNHOLD = "leg.unhold"
    LEG_COMMAND_FAILED = "leg.command_failed"
    LEG_STREAM_ADDED = "leg.stream_added"
    LEG_STREAM_REMOVED = "leg.stream_removed"
    LEG_STREAM_REJECTED = "leg.stream_rejected"
    LEG_STREAM_FAILED = "leg.stream_failed"
    LEG_STREAM_ROOM_CHANGED = "leg.stream_room_changed"
    LEG_STREAM_ROLE_CHANGED = "leg.stream_role_changed"
    SIPREC_SESSION_STARTED = "siprec.session_started"
    SIPREC_SESSION_ENDED = "siprec.session_ended"
    SIPREC_METADATA_UPDATED = "siprec.metadata_updated"
    SIPREC_PARTICIPANT_JOINED = "siprec.participant_joined"
    SIPREC_PARTICIPANT_LEFT = "siprec.participant_left"
    DTMF_RECEIVED = "dtmf.received"
    RTT_RECEIVED = "rtt.received"
    SPEAKING_STARTED = "speaking.started"
    SPEAKING_STOPPED = "speaking.stopped"
    PLAYBACK_STARTED = "playback.started"
    PLAYBACK_FINISHED = "playback.finished"
    PLAYBACK_ERROR = "playback.error"
    TTS_STARTED = "tts.started"
    TTS_FINISHED = "tts.finished"
    TTS_ERROR = "tts.error"
    TTS_STAGED = "tts.staged"
    TTS_DISCARDED = "tts.discarded"
    RECORDING_STARTED = "recording.started"
    RECORDING_FINISHED = "recording.finished"
    RECORDING_PAUSED = "recording.paused"
    RECORDING_RESUMED = "recording.resumed"
    LEG_TRANSFER_INITIATED = "leg.transfer_initiated"
    LEG_TRANSFER_REQUESTED = "leg.transfer_requested"
    LEG_TRANSFER_PROGRESS = "leg.transfer_progress"
    LEG_TRANSFER_COMPLETED = "leg.transfer_completed"
    LEG_TRANSFER_FAILED = "leg.transfer_failed"
    ROOM_CREATED = "room.created"
    ROOM_DELETED = "room.deleted"
    ROOM_BRIDGED = "room.bridged"
    ROOM_BRIDGE_UPDATED = "room.bridge_updated"
    ROOM_UNBRIDGED = "room.unbridged"
    ROOM_ROUTING_CHANGED = "room.routing_changed"
    LEG_ROLE_CHANGED = "leg.role_changed"
    STT_TEXT = "stt.text"
    STT_TURN = "stt.turn"
    AGENT_CONNECTED = "agent.connected"
    AGENT_DISCONNECTED = "agent.disconnected"
    AGENT_USER_TRANSCRIPT = "agent.user_transcript"
    AGENT_AGENT_RESPONSE = "agent.agent_response"
    AMD_RESULT = "amd.result"
    AMD_BEEP = "amd.beep"
    SIP_REGISTRATION_ATTEMPT = "sip.registration_attempt"
    SIP_REGISTRATION_ACTIVE = "sip.registration_active"
    SIP_REGISTRATION_EXPIRED = "sip.registration_expired"
    SIP_OUTBOUND_REGISTRATION_ACTIVE = "sip.outbound_registration_active"
    SIP_OUTBOUND_REGISTRATION_FAILED = "sip.outbound_registration_failed"
    SIP_OUTBOUND_REGISTRATION_EXPIRED = "sip.outbound_registration_expired"


class Leg(BaseModel):
    """Leg."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Instance identifier
    instance_id: str | None = None
    # Unique leg identifier (UUID)
    id: str
    # Leg type
    type: str
    # Leg state
    state: str
    # Room ID if the leg is in a room, empty otherwise
    room_id: str | None = None
    # Whether the leg is muted (cannot be heard by others)
    muted: bool
    # Whether the leg is deaf (cannot hear others)
    deaf: bool
    # Whether the leg receives DTMF digits broadcast from other legs in the same room. Defaults to true.
    accept_dtmf: bool
    # Whether the call is on hold (SIP legs only)
    held: bool
    # Routing role used by the room's audio routing matrix (e.g. "customer", "agent", "supervisor"). Empty string means unroled (full mesh).
    role: str | None = None
    # Application identifier for event stream filtering.
    app_id: str | None = None
    # Deprecated: X-* headers from the inbound INVITE. Only present on sip_inbound legs. Use `headers` for new code; it carries the same map plus surfaces handshake headers for websocket legs.
    sip_headers: dict[str, str] | None = None
    # Custom protocol headers exposed by the leg's transport — X-/P- headers from a SIP INVITE, the WebSocket upgrade request, or supplied at outbound dial time.
    headers: dict[str, str] | None = None
    # Opaque application JSON attached to the leg. Any JSON value is accepted (object, array, string, number, boolean). It is echoed on the leg view and carried at the top level of every event published for this leg, so external state can be correlated without keeping a leg_id lookup table. Capped by CUSTOM_DATA_MAX_BYTES (default 1024 bytes, 0 = unlimited).
    custom_data: Any = None

    _client: Client | None = PrivateAttr(default=None)


class Room(BaseModel):
    """Room."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Instance identifier
    instance_id: str | None = None
    # Room identifier
    id: str
    # Application identifier for event stream filtering.
    app_id: str | None = None
    # Mixer sample rate in Hz (8000, 16000, or 48000).
    sample_rate: int
    # Legs currently in this room
    participants: list[Leg]

    _client: Client | None = PrivateAttr(default=None)
