"""GENERATED by tools/generate.py from VoiceBlender openapi.yaml + asyncapi.yaml.

DO NOT EDIT — run ``make generate`` to regenerate.
"""

from __future__ import annotations

from voiceblender._client import Client
from voiceblender._http import path_escape
from voiceblender._models import Leg, Room
from voiceblender._requests import (
    ChallengeRequest,
    RegistrationAcceptRequest,
    RegistrationRejectRequest,
    RegistrationsResponse,
)
from voiceblender._responses import StatusResponse

__all__: list[str] = []

# SIP Registrations operations — bound onto Client / Leg / Room by class assignment.


async def _client_list_sip_registrations(self: Client) -> RegistrationsResponse:
    """List active SIP AOR registrations

    Returns every currently bound AOR contact, with the UDP/TCP/TLS socket on which the binding's REGISTER arrived. Use this list to know which AORs are dialable via the `to` field of POST /v1/legs.
    """
    out = await self._do("GET", "/sip/registrations", out_model=RegistrationsResponse)
    assert out is not None, "listSIPRegistrations" + ": empty response"
    return out


Client.list_sip_registrations = _client_list_sip_registrations  # type: ignore[method-assign]


async def _client_delete_sip_registration(self: Client, aor: str) -> StatusResponse:
    """Force-unbind an AOR (or a single contact within it)

    The AOR must be URL-encoded in the path (for example, `sip:alice@vb.example` is encoded as `sip%3Aalice%40vb.example`). Without query parameters, every Contact under the AOR is removed; with `?contact=<contact-uri>` only that single Contact is removed.
    """
    out = await self._do(
        "DELETE", f"/sip/registrations/{path_escape(aor)}", out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Client.delete_sip_registration = _client_delete_sip_registration  # type: ignore[method-assign]


async def _client_challenge_registration(
    self: Client, id: str, req: ChallengeRequest
) -> StatusResponse:
    """Challenge a parked inbound REGISTER with a 401 digest auth request

    Targets an inbound REGISTER surfaced via the `sip.registration_attempt` event (by its `attempt_id`). Sends a SIP 401 with a `WWW-Authenticate` digest challenge; the UA's credentialed re-REGISTER is verified against the supplied credential and, on success, bound and answered with 200 OK. Provide either `password` or `ha1`. The attempt must still be parked (it auto-accepts after the consult timeout).
    """
    out = await self._do(
        "POST", f"/sip/registrations/attempts/{id}/challenge", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Client.challenge_registration = _client_challenge_registration  # type: ignore[method-assign]


async def _client_accept_registration(
    self: Client, id: str, req: RegistrationAcceptRequest
) -> StatusResponse:
    """Accept a parked inbound REGISTER attempt

    Binds the AOR and replies 200 OK for an inbound REGISTER surfaced via the `sip.registration_attempt` event (by its `attempt_id`). Equivalent to letting the consult timeout elapse, but immediate. An optional `max_expires` caps the granted binding TTL.
    """
    out = await self._do(
        "POST", f"/sip/registrations/attempts/{id}/accept", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Client.accept_registration = _client_accept_registration  # type: ignore[method-assign]


async def _client_reject_registration(
    self: Client, id: str, req: RegistrationRejectRequest
) -> StatusResponse:
    """Reject a parked inbound REGISTER attempt

    Replies with a non-2xx (403 Forbidden by default; override via `code`/`reason`) for an inbound REGISTER surfaced via the `sip.registration_attempt` event (by its `attempt_id`).
    """
    out = await self._do(
        "POST", f"/sip/registrations/attempts/{id}/reject", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Client.reject_registration = _client_reject_registration  # type: ignore[method-assign]

_unused: tuple = (Leg, Room)
