"""GENERATED by tools/generate.py from VoiceBlender openapi.yaml + asyncapi.yaml.

DO NOT EDIT — run ``make generate`` to regenerate.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, JsonValue


class SIPAuth(BaseModel):
    """SIP digest authentication credentials."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    username: str = ""
    password: str


class CreateLegRequest(BaseModel):
    """CreateLegRequest."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Leg type
    type: str
    # Destination. For sip legs, a SIP URI (e.g. "sip:alice@example.com"). For whatsapp legs, an E.164 phone number (with or without '+').
    to: str | None = None
    # Deprecated alias for `to` (sip legs only). Prefer `to`.
    uri: str | None = None
    # Caller ID — sets the user part of the SIP From header (e.g. "+15551234567", "alice")
    from_: str | None = Field(default=None, alias="from")
    # SIP Privacy header value (e.g. "id", "none")
    privacy: str | None = None
    # Seconds to wait for answer; 0 = no timeout
    ring_timeout: int | None = None
    # Maximum call duration in seconds after connect. Automatically hung up when reached. 0 or omitted = no limit.
    max_duration: int | None = None
    # Codec preference order (sip legs only)
    codecs: list[str] | None = None
    # Custom headers to include in the outbound INVITE (sip/whatsapp) or the WebSocket upgrade request (websocket)
    headers: dict[str, str] | None = None
    # Room ID to auto-add the leg to once media is ready (early_media or connected). If the room does not exist, it is automatically created.
    room_id: str | None = None
    # Digest auth credentials. Required for whatsapp legs (Meta-issued password; username defaults to `from` with '+' stripped). Optional for sip legs (sipgo retries on 401/407 challenge).
    auth: SIPAuth | None = None
    # Route all events for this leg exclusively to this URL instead of global webhooks.
    webhook_url: str | None = None
    # HMAC-SHA256 signing secret for the per-leg webhook.
    webhook_secret: str | None = None
    # Enable Answering Machine Detection on outbound calls. Include the object (even empty) to enable with defaults; omit to disable.
    amd: AMDParams | None = None
    # If false, this leg will not receive DTMF digits broadcast from other legs in the same room. Defaults to true.
    accept_dtmf: bool | None = None
    # Application identifier. Carried through to all events for this leg. Use to filter the WebSocket event stream by app.
    app_id: str | None = None
    # If true, emit speaking.started and speaking.stopped events for this leg. If false, suppress them. Omit to use the server default (SPEECH_DETECTION_ENABLED env var, default false).
    speech_detection: bool | None = None
    # For sip legs: offer Real-Time Text (ITU-T T.140 over RTP per RFC 4103) alongside audio. For websocket legs: enable the bidirectional text-message channel. Default: false.
    rtt: bool | None = None
    # WebSocket target URL (ws:// or wss://) for outbound websocket legs. Required when type=websocket.
    url: str | None = None
    # PCM sample rate for websocket legs. The room's mixer automatically resamples between this and the room rate.
    sample_rate: int | None = None
    # Audio framing for websocket legs. `binary` ships raw PCM as WebSocket binary frames; `json_base64` wraps PCM as `{"type":"audio","audio":"<base64>"}` text frames (browser-friendly).
    wire_format: str | None = None
    # On-the-wire PCM sample encoding for websocket legs. v1 only supports `s16le`.
    sample_format: str | None = None


class AnswerLegRequest(BaseModel):
    """AnswerLegRequest."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # If true, emit speaking.started and speaking.stopped events for this leg. If false, suppress them. Omit to use the server default (SPEECH_DETECTION_ENABLED env var, default false).
    speech_detection: bool | None = None
    # Explicit codec for the answer SDP. Must appear in the remote offer's offered_codecs list. Omit to use the server's default preference order.
    codec: str | None = None


class EarlyMediaLegRequest(BaseModel):
    """EarlyMediaLegRequest."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Explicit codec for the 183 Session Progress SDP. Must appear in the remote offer's offered_codecs list. Omit to use the server's default preference order.
    codec: str | None = None


class DeleteLegRequest(BaseModel):
    """DeleteLegRequest."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Disconnect reason. Only honored for unanswered SIP inbound legs (state `ringing` or `early_media`); on connected legs the body is ignored and the leg is hung up with the legacy `api_hangup` reason. The value flows through to `leg.disconnected`'s `cdr.reason` and selects the SIP final response: `busy`→486, `declined`/`rejected`→603, `unavailable`→480, `not_found`→404, `forbidden`→403, `server_error`→500.
    reason: str | None = None


class TransferRequest(BaseModel):
    """TransferRequest."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # SIP URI to transfer the call to (e.g. "sip:bob@example.com").
    target: str
    # ID of an existing connected SIP leg whose dialog should be replaced (attended transfer). Omit for blind transfer.
    replaces_leg_id: str | None = None


class DTMFRequest(BaseModel):
    """DTMFRequest."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # DTMF digits to send (0-9, *, #)
    digits: str


class RTTRequest(BaseModel):
    """RTTRequest."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # UTF-8 text to send. May be one or more characters and may include T.140 control codes (e.g. backspace U+0008, CR/LF).
    text: str


class VolumeRequest(BaseModel):
    """VolumeRequest."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Volume adjustment (-8 to 8, ~3dB per step, 0 = unchanged)
    volume: int


class TTSRequest(BaseModel):
    """TTSRequest."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Text to synthesize
    text: str
    # Provider-specific voice identifier. ElevenLabs: voice name or ID. AWS Polly: voice ID (e.g. Joanna, Matthew). Google Cloud: voice name — either full format (e.g. en-US-Neural2-F) or short name for Gemini models (e.g. Achernar, Kore). Deepgram: model name (e.g. aura-2-asteria-en).
    voice: str
    # Provider-specific model/engine. ElevenLabs: model ID. AWS Polly: engine (standard, neural, long-form, generative; default neural). Google Cloud: model name (e.g. gemini-2.5-pro-tts, chirp3-hd).
    model_id: str
    # Language code (e.g. "en-US", "pl-pl"). Required for Google Gemini TTS voices that use short names (e.g. Achernar). Auto-extracted from full voice names like en-US-Neural2-F.
    language: str | None = None
    # Style/tone instruction for promptable voice models (Google Gemini TTS only). E.g. "Read aloud in a warm, welcoming tone."
    prompt: str | None = None
    # Volume adjustment in dB (-8 to 8)
    volume: int
    # TTS provider: "elevenlabs" (default), "aws", "google", or "deepgram"
    provider: str | None = None
    # ElevenLabs: API key override (falls back to ELEVENLABS_API_KEY env var). AWS: optional ACCESS_KEY:SECRET_KEY override (falls back to default AWS credential chain). Google Cloud: optional API key override (falls back to Application Default Credentials). Deepgram: API key override (falls back to DEEPGRAM_API_KEY env var).
    api_key: str | None = None


class STTRequest(BaseModel):
    """STTRequest."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Language code (e.g. "en", "es")
    language: str
    # Emit partial (non-final) transcripts
    partial: bool
    # STT provider: "elevenlabs" (default) or "deepgram"
    provider: str | None = None
    # API key override (falls back to ELEVENLABS_API_KEY or DEEPGRAM_API_KEY env var depending on provider)
    api_key: str | None = None


class DeepgramAgentRequest(BaseModel):
    """DeepgramAgentRequest."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Full Deepgram agent settings object (agent.listen, agent.think, agent.speak, etc.). When omitted, sensible defaults are used (nova-3 STT, gpt-4o-mini LLM, aura-2-asteria-en TTS).
    settings: JsonValue = None
    # Agent greeting message
    greeting: str | None = None
    # Language code (e.g. "en", "es")
    language: str | None = None
    # API key override (falls back to DEEPGRAM_API_KEY env var)
    api_key: str | None = None


class ElevenLabsAgentRequest(BaseModel):
    """ElevenLabsAgentRequest."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # ElevenLabs agent ID
    agent_id: str
    # Override the agent's first message
    first_message: str | None = None
    # Language code (e.g. "en", "es")
    language: str | None = None
    # Key-value pairs passed to the agent as dynamic variables
    dynamic_variables: dict[str, str] | None = None
    # API key override (falls back to ELEVENLABS_API_KEY env var)
    api_key: str | None = None


class PipecatAgentRequest(BaseModel):
    """PipecatAgentRequest."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # WebSocket URL of the Pipecat bot (e.g. ws://my-bot:8765)
    websocket_url: str


class VAPIAgentRequest(BaseModel):
    """VAPIAgentRequest."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # VAPI assistant ID
    assistant_id: str
    # Override the agent's first message
    first_message: str | None = None
    # Key-value pairs passed as VAPI variable values (assistantOverrides.variableValues)
    variable_values: dict[str, str] | None = None
    # API key override (falls back to VAPI_API_KEY env var)
    api_key: str | None = None


class AgentMessageRequest(BaseModel):
    """AgentMessageRequest."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Context or instruction to inject into the running agent session
    message: str


class AMDParams(BaseModel):
    """AMDParams."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Max milliseconds of silence before declaring no_speech
    initial_silence_timeout: int | None = None
    # Speech duration threshold (ms) above which answerer is classified as machine
    greeting_duration: int | None = None
    # Silence duration (ms) after initial speech to declare human
    after_greeting_silence: int | None = None
    # Max analysis window in milliseconds
    total_analysis_time: int | None = None
    # Minimum speech burst duration (ms) to count as a word
    minimum_word_length: int | None = None
    # Max time (ms) to wait for the voicemail beep after machine detection. 0 or omitted = disabled.
    beep_timeout: int | None = None


class RecordingRequest(BaseModel):
    """RecordingRequest."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # "file" (default) — local disk, "s3" — upload to S3 after recording stops
    storage: str
    # When true, record each participant to a separate mono WAV file in addition to the full mix. Only applies to room recordings.
    multi_channel: bool
    # S3 bucket name. Overrides S3_BUCKET env var. Required if env var is not set.
    s_3_bucket: str = Field(alias="s3_bucket")
    # AWS region. Overrides S3_REGION env var. Default us-east-1.
    s_3_region: str = Field(alias="s3_region")
    # Custom S3 endpoint (MinIO, etc.). Overrides S3_ENDPOINT env var.
    s_3_endpoint: str = Field(alias="s3_endpoint")
    # Key prefix (e.g. recordings/). Overrides S3_PREFIX env var.
    s_3_prefix: str = Field(alias="s3_prefix")
    # AWS access key ID. Overrides default credential chain.
    s_3_access_key: str = Field(alias="s3_access_key")
    # AWS secret access key. Must be set together with s3_access_key.
    s_3_secret_key: str = Field(alias="s3_secret_key")


class WebRTCOfferRequest(BaseModel):
    """WebRTCOfferRequest."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # SDP offer from the browser
    sdp: str


class CreateRoomRequest(BaseModel):
    """CreateRoomRequest."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Custom room ID (auto-generated UUID if omitted)
    id: str
    # Route all events for this room exclusively to this URL instead of global webhooks.
    webhook_url: str | None = None
    # HMAC-SHA256 signing secret for the per-room webhook.
    webhook_secret: str | None = None
    # Application identifier. Carried through to all events for this room. Use to filter the WebSocket event stream by app.
    app_id: str | None = None
    # Mixer sample rate in Hz. Allowed values: 8000, 16000, 48000. Default: 16000.
    sample_rate: int | None = None


class AddLegRequest(BaseModel):
    """AddLegRequest."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # ID of the leg to add
    leg_id: str
    # If set, apply this mute state to the leg atomically before it joins the mixer (no race where un-muted audio enters the mix). Omit to leave current state untouched (useful when moving between rooms).
    mute: bool | None = None
    # If set, apply this deaf state to the leg atomically before it joins the mixer. Omit to leave current state untouched.
    deaf: bool | None = None
    # If set, control whether this leg receives DTMF digits broadcast from other legs in the same room. Omit to leave current state untouched (default for new legs is true).
    accept_dtmf: bool | None = None
    # If set, apply this routing role to the leg atomically before it joins the mixer. The room's routing matrix (see PUT /v1/rooms/{id}/routing) decides which other legs this leg hears and is heard by based on roles. Pass "" to clear the role (full mesh). Omit to leave the current role untouched.
    role: str | None = None


class ICECandidateInit(BaseModel):
    """WebRTC ICE candidate initialisation."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    candidate: str
    sdp_mid: str | None = Field(default=None, alias="sdpMid")
    sdp_m_line_index: int | None = Field(default=None, alias="sdpMLineIndex")
    username_fragment: str | None = Field(default=None, alias="usernameFragment")
