"""GENERATED by tools/generate.py from VoiceBlender openapi.yaml + asyncapi.yaml.

DO NOT EDIT — run ``make generate`` to regenerate.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class StatusResponse(BaseModel):
    """StatusResponse."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    # Instance identifier
    instance_id: str | None = None
    status: str
