"""GENERATED by tools/generate.py from VoiceBlender openapi.yaml + asyncapi.yaml.

DO NOT EDIT — run ``make generate`` to regenerate.
"""

from __future__ import annotations

from voiceblender._client import Client
from voiceblender._models import Leg, Room
from voiceblender._playback import PlaybackRequest
from voiceblender._requests import (
    AddLegRequest,
    AgentMessageRequest,
    CreateRoomRequest,
    DeepgramAgentRequest,
    ElevenLabsAgentRequest,
    PipecatAgentRequest,
    RecordingRequest,
    STTRequest,
    TTSRequest,
    VAPIAgentRequest,
    VolumeRequest,
)
from voiceblender._responses import StatusResponse
from voiceblender._responses_extra import (
    AddLegResponse,
    PlaybackResponse,
    RecordingResponse,
    TTSResponse,
)

__all__: list[str] = []

# Rooms operations — bound onto Client / Leg / Room by class assignment.


async def _client_list_rooms(self: Client) -> list[Room]:
    """List all rooms with participants"""
    return await self._do_list("GET", "/rooms", item_model=Room)


Client.list_rooms = _client_list_rooms  # type: ignore[method-assign]


async def _client_create_room(self: Client, req: CreateRoomRequest) -> Room:
    """Create a room"""
    out = await self._do("POST", "/rooms", body=req, out_model=Room)
    if out is not None:
        out._client = self
    assert out is not None, "createRoom" + ": empty response"
    return out


Client.create_room = _client_create_room  # type: ignore[method-assign]


async def _client_get_room(self: Client, id: str) -> Room:
    """Get a room with participants"""
    out = await self._do("GET", f"/rooms/{id}", out_model=Room)
    if out is not None:
        out._client = self
    assert out is not None, "getRoom" + ": empty response"
    return out


Client.get_room = _client_get_room  # type: ignore[method-assign]


async def _room_delete(self: Room) -> StatusResponse:
    """Delete a room"""
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("DELETE", f"/rooms/{self.id}", out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Room.delete = _room_delete  # type: ignore[method-assign]


async def _room_add_leg(self: Room, req: AddLegRequest) -> AddLegResponse:
    """Add or move a leg to a room

    Add a leg to a room (auto-creates room if it doesn't exist). If the leg is already in a different room, it is atomically moved to the target room. A ringing inbound SIP leg is automatically answered before being added — in this case the response status is `adding` and the actual room join happens asynchronously, observable via `leg.joined_room`. Auto-answer failures surface as `leg.command_failed` with `command="add_to_room"`.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/rooms/{self.id}/legs", body=req, out_model=AddLegResponse
    )
    assert out is not None, "addLegToRoom" + ": empty response"
    return out


Room.add_leg = _room_add_leg  # type: ignore[method-assign]


async def _room_remove_leg(self: Room, leg_id: str) -> StatusResponse:
    """Remove a leg from a room"""
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "DELETE", f"/rooms/{self.id}/legs/{leg_id}", out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Room.remove_leg = _room_remove_leg  # type: ignore[method-assign]


async def _room_play(self: Room, req: PlaybackRequest) -> PlaybackResponse:
    """Play audio to a room"""
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/rooms/{self.id}/play", body=req, out_model=PlaybackResponse
    )
    assert out is not None, "playRoom" + ": empty response"
    return out


Room.play = _room_play  # type: ignore[method-assign]


async def _room_volume_play(self: Room, playback_id: str, req: VolumeRequest) -> StatusResponse:
    """Change the volume of an active room playback"""
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "PATCH", f"/rooms/{self.id}/play/{playback_id}", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Room.volume_play = _room_volume_play  # type: ignore[method-assign]


async def _room_stop_play(self: Room, playback_id: str) -> StatusResponse:
    """Stop room playback"""
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "DELETE", f"/rooms/{self.id}/play/{playback_id}", out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Room.stop_play = _room_stop_play  # type: ignore[method-assign]


async def _room_play_tts(self: Room, req: TTSRequest) -> TTSResponse:
    """Synthesize speech and play it into a room

    Synthesizes the provided text using the configured TTS provider and plays the audio into the room. When `TTS_CACHE_ENABLED=true`, identical requests (same text, voice, model, language, and prompt) are stored on disk in `TTS_CACHE_DIR` and persist across restarts, without calling the external provider.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("POST", f"/rooms/{self.id}/tts", body=req, out_model=TTSResponse)
    assert out is not None, "ttsRoom" + ": empty response"
    return out


Room.play_tts = _room_play_tts  # type: ignore[method-assign]


async def _room_record(self: Room, req: RecordingRequest) -> RecordingResponse:
    """Start recording the room mix to a WAV file

    Records the full room mix at 16kHz, 16-bit, mono.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/rooms/{self.id}/record", body=req, out_model=RecordingResponse
    )
    assert out is not None, "recordRoom" + ": empty response"
    return out


Room.record = _room_record  # type: ignore[method-assign]


async def _room_stop_record(self: Room) -> RecordingResponse:
    """Stop room recording"""
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("DELETE", f"/rooms/{self.id}/record", out_model=RecordingResponse)
    assert out is not None, "stopRecordRoom" + ": empty response"
    return out


Room.stop_record = _room_stop_record  # type: ignore[method-assign]


async def _room_pause_record(self: Room) -> StatusResponse:
    """Pause a room recording

    Replaces the room mix with silence on the active recording until `/record/resume` is called. When multi-channel recording is active, every per-participant track is paused too (including tracks for participants who join while paused). Idempotent: returns `status: already_paused` when already paused.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("POST", f"/rooms/{self.id}/record/pause", out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Room.pause_record = _room_pause_record  # type: ignore[method-assign]


async def _room_resume_record(self: Room) -> StatusResponse:
    """Resume a paused room recording

    Resumes writing real audio after a prior `/record/pause`. Resumes every per-participant track if multi-channel recording is active. Idempotent.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/rooms/{self.id}/record/resume", out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Room.resume_record = _room_resume_record  # type: ignore[method-assign]


async def _room_stt(self: Room, req: STTRequest) -> StatusResponse:
    """Start speech-to-text on all room participants"""
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/rooms/{self.id}/stt", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Room.stt = _room_stt  # type: ignore[method-assign]


async def _room_stop_stt(self: Room) -> StatusResponse:
    """Stop speech-to-text on a room"""
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("DELETE", f"/rooms/{self.id}/stt", out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Room.stop_stt = _room_stop_stt  # type: ignore[method-assign]


async def _room_elevenlabs_agent(self: Room, req: ElevenLabsAgentRequest) -> StatusResponse:
    """Attach an ElevenLabs ConvAI agent to a room

    The agent joins as a virtual participant, hearing all participants (mixed-minus-self) and speaking to everyone.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/rooms/{self.id}/agent/elevenlabs", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Room.elevenlabs_agent = _room_elevenlabs_agent  # type: ignore[method-assign]


async def _room_vapi_agent(self: Room, req: VAPIAgentRequest) -> StatusResponse:
    """Attach a VAPI agent to a room

    The agent joins as a virtual participant, hearing all participants (mixed-minus-self) and speaking to everyone.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/rooms/{self.id}/agent/vapi", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Room.vapi_agent = _room_vapi_agent  # type: ignore[method-assign]


async def _room_pipecat_agent(self: Room, req: PipecatAgentRequest) -> StatusResponse:
    """Attach a Pipecat bot to a room

    The bot joins as a virtual participant via WebSocket, hearing all participants (mixed-minus-self) and speaking to everyone.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/rooms/{self.id}/agent/pipecat", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Room.pipecat_agent = _room_pipecat_agent  # type: ignore[method-assign]


async def _room_deepgram_agent(self: Room, req: DeepgramAgentRequest) -> StatusResponse:
    """Attach a Deepgram Voice Agent to a room

    The agent joins as a virtual participant, hearing all participants (mixed-minus-self) and speaking to everyone.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/rooms/{self.id}/agent/deepgram", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Room.deepgram_agent = _room_deepgram_agent  # type: ignore[method-assign]


async def _room_agent_message(self: Room, req: AgentMessageRequest) -> StatusResponse:
    """Inject a message into a running agent session on a room

    Sends a context message or instruction to the running agent. Supported by Deepgram (InjectAgentMessage), Pipecat (TextFrame), and VAPI (control URL). Returns 501 for ElevenLabs.
    """
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/rooms/{self.id}/agent/message", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Room.agent_message = _room_agent_message  # type: ignore[method-assign]


async def _room_stop_agent(self: Room) -> StatusResponse:
    """Detach the agent from a room"""
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do("DELETE", f"/rooms/{self.id}/agent", out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Room.stop_agent = _room_stop_agent  # type: ignore[method-assign]

_unused: tuple = (Leg, Room)
