"""GENERATED by tools/generate.py from VoiceBlender openapi.yaml + asyncapi.yaml.

DO NOT EDIT — run ``make generate`` to regenerate.
"""

from __future__ import annotations

from voiceblender._client import Client
from voiceblender._models import Leg, Room
from voiceblender._requests import (
    CreateTrunkRequest,
    CreateTrunkResponse,
    TrunksListResponse,
    TrunkView,
)
from voiceblender._responses import StatusResponse

__all__: list[str] = []

# SIP Trunks operations — bound onto Client / Leg / Room by class assignment.


async def _client_list_sip_trunks(self: Client) -> TrunksListResponse:
    """List configured SIP trunks"""
    out = await self._do("GET", "/sip/trunks", out_model=TrunksListResponse)
    assert out is not None, "listSIPTrunks" + ": empty response"
    return out


Client.list_sip_trunks = _client_list_sip_trunks  # type: ignore[method-assign]


async def _client_create_sip_trunk(self: Client, req: CreateTrunkRequest) -> CreateTrunkResponse:
    """Create an outbound SIP trunk (REGISTER or static peering)

    Creates a typed SIP trunk. For `type: "sip_register"`, VoiceBlender begins REGISTERing to the supplied registrar URI with digest auth, refreshes before expiry, and routes inbound INVITEs that arrive on that peer's socket plus outbound INVITEs whose `from` matches the AOR through the trunk. Set `sip_register.outbound_proxy` to send both the REGISTER and those INVITEs via a next-hop proxy instead of straight at the registrar; the Request-URI and digest authentication still target `registrar_uri`. It defaults to `SIP_OUTBOUND_PROXY` and is resolved at creation time, so the trunk snapshot reports the hop actually in effect. For `type: "ip_ip"`, returns 501 (reserved, not yet implemented).
    """
    out = await self._do("POST", "/sip/trunks", body=req, out_model=CreateTrunkResponse)
    assert out is not None, "createSIPTrunk" + ": empty response"
    return out


Client.create_sip_trunk = _client_create_sip_trunk  # type: ignore[method-assign]


async def _client_get_sip_trunk(self: Client, id: str) -> TrunkView:
    """Get a single SIP trunk"""
    out = await self._do("GET", f"/sip/trunks/{id}", out_model=TrunkView)
    assert out is not None, "getSIPTrunk" + ": empty response"
    return out


Client.get_sip_trunk = _client_get_sip_trunk  # type: ignore[method-assign]


async def _client_delete_sip_trunk(self: Client, id: str) -> StatusResponse:
    """Unregister and remove a SIP trunk

    Returns 202 Accepted; the unregister (REGISTER with Expires: 0) and final removal run asynchronously.
    """
    out = await self._do("DELETE", f"/sip/trunks/{id}", out_model=StatusResponse)
    return out if out is not None else StatusResponse(status="ok")


Client.delete_sip_trunk = _client_delete_sip_trunk  # type: ignore[method-assign]

_unused: tuple = (Leg, Room)
