"""GENERATED by tools/generate.py from VoiceBlender openapi.yaml + asyncapi.yaml.

DO NOT EDIT — run ``make generate`` to regenerate.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field, JsonValue

from voiceblender._requests import (
    CreateLegRequest,
    CreateRoomRequest,
    ICECandidateInit,
    WebRTCOfferRequest,
)
from voiceblender._stream import EventStream

# ── VSI payload / result schemas ──────────────────────────────────────


class AddLegPayload(BaseModel):
    """AddLegPayload."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    room_id: str
    leg_id: str
    mute: bool | None = None
    deaf: bool | None = None
    accept_dtmf: bool | None = None


class AddLegToRoomResult(BaseModel):
    """AddLegToRoomResult."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    status: str | None = None
    room_id: str | None = None
    leg_id: str | None = None


class AgentDeepgramPayload(BaseModel):
    """AgentDeepgramPayload."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    id: str
    settings: dict[str, Any] | None = None
    greeting: str | None = None
    language: str | None = None
    api_key: str | None = None


class AgentElevenLabsPayload(BaseModel):
    """AgentElevenLabsPayload."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    id: str
    agent_id: str
    first_message: str | None = None
    language: str | None = None
    dynamic_variables: dict[str, str] | None = None
    api_key: str | None = None


class AgentMessagePayload(BaseModel):
    """AgentMessagePayload."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    id: str
    message: str


class AgentMessageResult(BaseModel):
    """AgentMessageResult."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    status: str | None = None


class AgentPipecatPayload(BaseModel):
    """AgentPipecatPayload."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    id: str
    websocket_url: str


class AgentStartLegResult(BaseModel):
    """AgentStartLegResult."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    status: str | None = None
    leg_id: str | None = None


class AgentStartRoomResult(BaseModel):
    """AgentStartRoomResult."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    status: str | None = None
    room_id: str | None = None


class AgentStopResult(BaseModel):
    """AgentStopResult."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    status: str | None = None


class AgentVAPIPayload(BaseModel):
    """AgentVAPIPayload."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    id: str
    assistant_id: str
    first_message: str | None = None
    variable_values: dict[str, str] | None = None
    api_key: str | None = None


class AnswerLegPayload(BaseModel):
    """AnswerLegPayload."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    id: str
    speech_detection: bool | None = None
    codec: str | None = None


class BridgeCreatePayload(BaseModel):
    """BridgeCreatePayload."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    room_id: str
    bridge_id: str | None = None
    peer_room_id: str
    direction: str | None = None


class BridgeListPayload(BaseModel):
    """BridgeListPayload."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    room_id: str


class BridgeRefPayload(BaseModel):
    """BridgeRefPayload."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    room_id: str
    bridge_id: str


class BridgeUpdatePayload(BaseModel):
    """BridgeUpdatePayload."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    room_id: str
    bridge_id: str
    direction: str


class BridgeView(BaseModel):
    """BridgeView."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    id: str
    room_id: str
    direction: str
    sample_rate: int


class ChannelInfo(BaseModel):
    """ChannelInfo."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    channel: int
    start_ms: int
    end_ms: int


class DTMFPayload(BaseModel):
    """DTMFPayload."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    id: str
    digits: str


class DeleteLegPayload(BaseModel):
    """DeleteLegPayload."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    id: str
    reason: str | None = None


class EarlyMediaPayload(BaseModel):
    """EarlyMediaPayload."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    id: str
    codec: str | None = None


class IDPayload(BaseModel):
    """IDPayload."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    id: str


class LegAMDStartPayload(BaseModel):
    """LegAMDStartPayload."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    id: str
    initial_silence_timeout: int | None = None
    greeting_duration: int | None = None
    after_greeting_silence: int | None = None
    total_analysis_time: int | None = None
    minimum_word_length: int | None = None
    beep_timeout: int | None = None


class PlaybackStartPayload(BaseModel):
    """PlaybackStartPayload."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    id: str
    url: str
    tone: str
    mime_type: str
    repeat: int
    volume: int


class PlaybackStartResult(BaseModel):
    """PlaybackStartResult."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    playback_id: str | None = None
    status: str | None = None


class PlaybackStopResult(BaseModel):
    """PlaybackStopResult."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    status: str | None = None


class PlaybackTargetPayload(BaseModel):
    """PlaybackTargetPayload."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    id: str
    playback_id: str


class PlaybackVolumePayload(BaseModel):
    """PlaybackVolumePayload."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    id: str
    playback_id: str
    volume: int


class RTTPayload(BaseModel):
    """RTTPayload."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    id: str
    text: str


class RecordStartPayload(BaseModel):
    """RecordStartPayload."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    id: str
    storage: str
    multi_channel: bool
    s_3_bucket: str = Field(alias="s3_bucket")
    s_3_region: str = Field(alias="s3_region")
    s_3_endpoint: str = Field(alias="s3_endpoint")
    s_3_prefix: str = Field(alias="s3_prefix")
    s_3_access_key: str = Field(alias="s3_access_key")
    s_3_secret_key: str = Field(alias="s3_secret_key")


class RecordingPauseResumeResult(BaseModel):
    """RecordingPauseResumeResult."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    status: str | None = None


class RecordingStartResult(BaseModel):
    """RecordingStartResult."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    status: str | None = None
    file: str | None = None


class RecordingStopLegResult(BaseModel):
    """RecordingStopLegResult."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    status: str | None = None
    file: str | None = None


class RecordingStopRoomResult(BaseModel):
    """RecordingStopRoomResult."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    status: str | None = None
    file: str | None = None
    multi_channel_file: str | None = None
    channels: dict[str, ChannelInfo] | None = None


class RoomLegPayload(BaseModel):
    """RoomLegPayload."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    room_id: str
    leg_id: str


class STTStartLegResult(BaseModel):
    """STTStartLegResult."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    status: str | None = None
    leg_id: str | None = None


class STTStartPayload(BaseModel):
    """STTStartPayload."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    id: str
    language: str
    partial: bool
    provider: str | None = None
    api_key: str | None = None


class STTStartRoomResult(BaseModel):
    """STTStartRoomResult."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    status: str | None = None
    room_id: str | None = None
    leg_ids: list[str] | None = None


class STTStopResult(BaseModel):
    """STTStopResult."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    status: str | None = None


class TTSStartPayload(BaseModel):
    """TTSStartPayload."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    id: str
    text: str
    voice: str
    model_id: str
    language: str | None = None
    prompt: str | None = None
    volume: int
    provider: str | None = None
    api_key: str | None = None


class TTSStartResult(BaseModel):
    """TTSStartResult."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    tts_id: str | None = None
    status: str | None = None


class TransferLegPayload(BaseModel):
    """TransferLegPayload."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    id: str
    target: str
    replaces_leg_id: str | None = None


class TransferLegResult(BaseModel):
    """TransferLegResult."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    status: str | None = None


class VSIStatusResponse(BaseModel):
    """VSIStatusResponse."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    status: str | None = None


class VSIWebRTCAddCandidatePayload(BaseModel):
    """VSIWebRTCAddCandidatePayload."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    id: str
    candidate: ICECandidateInit


class WebRTCCandidatesResult(BaseModel):
    """WebRTCCandidatesResult."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    candidates: list[ICECandidateInit] | None = None
    done: bool | None = None


class WebRTCOfferResult(BaseModel):
    """WebRTCOfferResult."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    leg_id: str | None = None
    sdp: str | None = None


# ── VSI command methods on EventStream ────────────────────────────────


async def _vsi_list_legs(self: EventStream) -> list[JsonValue]:
    """List all active legs"""
    return await self._call("list_legs", None)  # type: ignore[no-any-return]


EventStream.list_legs = _vsi_list_legs  # type: ignore[method-assign]


async def _vsi_get_leg(self: EventStream, payload: IDPayload) -> JsonValue:
    """Get a single leg by id"""
    return await self._call("get_leg", payload)  # type: ignore[no-any-return]


EventStream.get_leg = _vsi_get_leg  # type: ignore[method-assign]


async def _vsi_create_leg(self: EventStream, payload: CreateLegRequest) -> JsonValue:
    """Originate an outbound leg"""
    return await self._call("create_leg", payload)  # type: ignore[no-any-return]


EventStream.create_leg = _vsi_create_leg  # type: ignore[method-assign]


async def _vsi_answer_leg(self: EventStream, payload: AnswerLegPayload) -> VSIStatusResponse:
    """Answer a ringing inbound leg"""
    out = await self._call("answer_leg", payload, result_model=VSIStatusResponse)
    return out  # type: ignore[no-any-return]


EventStream.answer_leg = _vsi_answer_leg  # type: ignore[method-assign]


async def _vsi_delete_leg(self: EventStream, payload: DeleteLegPayload) -> VSIStatusResponse:
    """Hang up a leg"""
    out = await self._call("delete_leg", payload, result_model=VSIStatusResponse)
    return out  # type: ignore[no-any-return]


EventStream.delete_leg = _vsi_delete_leg  # type: ignore[method-assign]


async def _vsi_mute_leg(self: EventStream, payload: IDPayload) -> VSIStatusResponse:
    """Mute a leg"""
    out = await self._call("mute_leg", payload, result_model=VSIStatusResponse)
    return out  # type: ignore[no-any-return]


EventStream.mute_leg = _vsi_mute_leg  # type: ignore[method-assign]


async def _vsi_unmute_leg(self: EventStream, payload: IDPayload) -> VSIStatusResponse:
    """Unmute a leg"""
    out = await self._call("unmute_leg", payload, result_model=VSIStatusResponse)
    return out  # type: ignore[no-any-return]


EventStream.unmute_leg = _vsi_unmute_leg  # type: ignore[method-assign]


async def _vsi_deaf_leg(self: EventStream, payload: IDPayload) -> VSIStatusResponse:
    """Deafen a leg (stop receiving room audio)"""
    out = await self._call("deaf_leg", payload, result_model=VSIStatusResponse)
    return out  # type: ignore[no-any-return]


EventStream.deaf_leg = _vsi_deaf_leg  # type: ignore[method-assign]


async def _vsi_undeaf_leg(self: EventStream, payload: IDPayload) -> VSIStatusResponse:
    """Undeafen a leg"""
    out = await self._call("undeaf_leg", payload, result_model=VSIStatusResponse)
    return out  # type: ignore[no-any-return]


EventStream.undeaf_leg = _vsi_undeaf_leg  # type: ignore[method-assign]


async def _vsi_hold_leg(self: EventStream, payload: IDPayload) -> VSIStatusResponse:
    """Put a SIP leg on hold"""
    out = await self._call("hold_leg", payload, result_model=VSIStatusResponse)
    return out  # type: ignore[no-any-return]


EventStream.hold_leg = _vsi_hold_leg  # type: ignore[method-assign]


async def _vsi_unhold_leg(self: EventStream, payload: IDPayload) -> VSIStatusResponse:
    """Resume a held SIP leg"""
    out = await self._call("unhold_leg", payload, result_model=VSIStatusResponse)
    return out  # type: ignore[no-any-return]


EventStream.unhold_leg = _vsi_unhold_leg  # type: ignore[method-assign]


async def _vsi_send_leg_dtmf(self: EventStream, payload: DTMFPayload) -> VSIStatusResponse:
    """Send DTMF digits on a leg"""
    out = await self._call("send_leg_dtmf", payload, result_model=VSIStatusResponse)
    return out  # type: ignore[no-any-return]


EventStream.send_leg_dtmf = _vsi_send_leg_dtmf  # type: ignore[method-assign]


async def _vsi_accept_leg_dtmf(self: EventStream, payload: IDPayload) -> VSIStatusResponse:
    """Enable DTMF reception"""
    out = await self._call("accept_leg_dtmf", payload, result_model=VSIStatusResponse)
    return out  # type: ignore[no-any-return]


EventStream.accept_leg_dtmf = _vsi_accept_leg_dtmf  # type: ignore[method-assign]


async def _vsi_reject_leg_dtmf(self: EventStream, payload: IDPayload) -> VSIStatusResponse:
    """Disable DTMF reception"""
    out = await self._call("reject_leg_dtmf", payload, result_model=VSIStatusResponse)
    return out  # type: ignore[no-any-return]


EventStream.reject_leg_dtmf = _vsi_reject_leg_dtmf  # type: ignore[method-assign]


async def _vsi_send_leg_rtt(self: EventStream, payload: RTTPayload) -> VSIStatusResponse:
    """Send Real-Time Text (T.140) on a SIP leg"""
    out = await self._call("send_leg_rtt", payload, result_model=VSIStatusResponse)
    return out  # type: ignore[no-any-return]


EventStream.send_leg_rtt = _vsi_send_leg_rtt  # type: ignore[method-assign]


async def _vsi_accept_leg_rtt(self: EventStream, payload: IDPayload) -> VSIStatusResponse:
    """Enable RTT reception"""
    out = await self._call("accept_leg_rtt", payload, result_model=VSIStatusResponse)
    return out  # type: ignore[no-any-return]


EventStream.accept_leg_rtt = _vsi_accept_leg_rtt  # type: ignore[method-assign]


async def _vsi_reject_leg_rtt(self: EventStream, payload: IDPayload) -> VSIStatusResponse:
    """Disable RTT reception"""
    out = await self._call("reject_leg_rtt", payload, result_model=VSIStatusResponse)
    return out  # type: ignore[no-any-return]


EventStream.reject_leg_rtt = _vsi_reject_leg_rtt  # type: ignore[method-assign]


async def _vsi_webrtc_offer(self: EventStream, payload: WebRTCOfferRequest) -> WebRTCOfferResult:
    """Establish a WebRTC leg via SDP offer/answer"""
    out = await self._call("webrtc_offer", payload, result_model=WebRTCOfferResult)
    return out  # type: ignore[no-any-return]


EventStream.webrtc_offer = _vsi_webrtc_offer  # type: ignore[method-assign]


async def _vsi_webrtc_add_candidate(
    self: EventStream, payload: VSIWebRTCAddCandidatePayload
) -> VSIStatusResponse:
    """Add a remote ICE candidate to a WebRTC leg"""
    out = await self._call("webrtc_add_candidate", payload, result_model=VSIStatusResponse)
    return out  # type: ignore[no-any-return]


EventStream.webrtc_add_candidate = _vsi_webrtc_add_candidate  # type: ignore[method-assign]


async def _vsi_webrtc_get_candidates(
    self: EventStream, payload: IDPayload
) -> WebRTCCandidatesResult:
    """Drain server-gathered ICE candidates for a WebRTC leg"""
    out = await self._call("webrtc_get_candidates", payload, result_model=WebRTCCandidatesResult)
    return out  # type: ignore[no-any-return]


EventStream.webrtc_get_candidates = _vsi_webrtc_get_candidates  # type: ignore[method-assign]


async def _vsi_list_rooms(self: EventStream) -> list[JsonValue]:
    """List all rooms"""
    return await self._call("list_rooms", None)  # type: ignore[no-any-return]


EventStream.list_rooms = _vsi_list_rooms  # type: ignore[method-assign]


async def _vsi_get_room(self: EventStream, payload: IDPayload) -> JsonValue:
    """Get a single room by id"""
    return await self._call("get_room", payload)  # type: ignore[no-any-return]


EventStream.get_room = _vsi_get_room  # type: ignore[method-assign]


async def _vsi_create_room(self: EventStream, payload: CreateRoomRequest) -> JsonValue:
    """Create a room"""
    return await self._call("create_room", payload)  # type: ignore[no-any-return]


EventStream.create_room = _vsi_create_room  # type: ignore[method-assign]


async def _vsi_delete_room(self: EventStream, payload: IDPayload) -> VSIStatusResponse:
    """Delete a room"""
    out = await self._call("delete_room", payload, result_model=VSIStatusResponse)
    return out  # type: ignore[no-any-return]


EventStream.delete_room = _vsi_delete_room  # type: ignore[method-assign]


async def _vsi_add_leg_to_room(self: EventStream, payload: AddLegPayload) -> AddLegToRoomResult:
    """Add or move a leg into a room"""
    out = await self._call("add_leg_to_room", payload, result_model=AddLegToRoomResult)
    return out  # type: ignore[no-any-return]


EventStream.add_leg_to_room = _vsi_add_leg_to_room  # type: ignore[method-assign]


async def _vsi_remove_leg_from_room(
    self: EventStream, payload: RoomLegPayload
) -> VSIStatusResponse:
    """Remove a leg from a room"""
    out = await self._call("remove_leg_from_room", payload, result_model=VSIStatusResponse)
    return out  # type: ignore[no-any-return]


EventStream.remove_leg_from_room = _vsi_remove_leg_from_room  # type: ignore[method-assign]


async def _vsi_bridge_create(self: EventStream, payload: BridgeCreatePayload) -> BridgeView:
    """Join two rooms' mixers"""
    out = await self._call("bridge_create", payload, result_model=BridgeView)
    return out  # type: ignore[no-any-return]


EventStream.bridge_create = _vsi_bridge_create  # type: ignore[method-assign]


async def _vsi_bridge_list(self: EventStream, payload: BridgeListPayload) -> list[BridgeView]:
    """List bridges involving a room"""
    return await self._call("bridge_list", payload)  # type: ignore[no-any-return]


EventStream.bridge_list = _vsi_bridge_list  # type: ignore[method-assign]


async def _vsi_bridge_get(self: EventStream, payload: BridgeRefPayload) -> BridgeView:
    """Get a bridge involving a room"""
    out = await self._call("bridge_get", payload, result_model=BridgeView)
    return out  # type: ignore[no-any-return]


EventStream.bridge_get = _vsi_bridge_get  # type: ignore[method-assign]


async def _vsi_bridge_update(self: EventStream, payload: BridgeUpdatePayload) -> BridgeView:
    """Change a bridge's direction"""
    out = await self._call("bridge_update", payload, result_model=BridgeView)
    return out  # type: ignore[no-any-return]


EventStream.bridge_update = _vsi_bridge_update  # type: ignore[method-assign]


async def _vsi_bridge_delete(self: EventStream, payload: BridgeRefPayload) -> VSIStatusResponse:
    """Tear down a bridge"""
    out = await self._call("bridge_delete", payload, result_model=VSIStatusResponse)
    return out  # type: ignore[no-any-return]


EventStream.bridge_delete = _vsi_bridge_delete  # type: ignore[method-assign]


async def _vsi_leg_ring(self: EventStream, payload: IDPayload) -> VSIStatusResponse:
    """Send a 180 Ringing on a SIP inbound leg"""
    out = await self._call("leg_ring", payload, result_model=VSIStatusResponse)
    return out  # type: ignore[no-any-return]


EventStream.leg_ring = _vsi_leg_ring  # type: ignore[method-assign]


async def _vsi_leg_early_media(self: EventStream, payload: EarlyMediaPayload) -> VSIStatusResponse:
    """Enable early media (183 Session Progress) on a SIP inbound leg"""
    out = await self._call("leg_early_media", payload, result_model=VSIStatusResponse)
    return out  # type: ignore[no-any-return]


EventStream.leg_early_media = _vsi_leg_early_media  # type: ignore[method-assign]


async def _vsi_leg_amd_start(self: EventStream, payload: LegAMDStartPayload) -> VSIStatusResponse:
    """Start Answering Machine Detection on a connected SIP leg"""
    out = await self._call("leg_amd_start", payload, result_model=VSIStatusResponse)
    return out  # type: ignore[no-any-return]


EventStream.leg_amd_start = _vsi_leg_amd_start  # type: ignore[method-assign]


async def _vsi_leg_record_start(
    self: EventStream, payload: RecordStartPayload
) -> RecordingStartResult:
    """Start recording a leg (stereo when in a room or SIP, mono otherwise)"""
    out = await self._call("leg_record_start", payload, result_model=RecordingStartResult)
    return out  # type: ignore[no-any-return]


EventStream.leg_record_start = _vsi_leg_record_start  # type: ignore[method-assign]


async def _vsi_room_record_start(
    self: EventStream, payload: RecordStartPayload
) -> RecordingStartResult:
    """Start recording the full room mix (mono; multi_channel adds per-participant tracks)"""
    out = await self._call("room_record_start", payload, result_model=RecordingStartResult)
    return out  # type: ignore[no-any-return]


EventStream.room_record_start = _vsi_room_record_start  # type: ignore[method-assign]


async def _vsi_leg_record_pause(
    self: EventStream, payload: IDPayload
) -> RecordingPauseResumeResult:
    """Pause a leg recording"""
    out = await self._call("leg_record_pause", payload, result_model=RecordingPauseResumeResult)
    return out  # type: ignore[no-any-return]


EventStream.leg_record_pause = _vsi_leg_record_pause  # type: ignore[method-assign]


async def _vsi_leg_record_resume(
    self: EventStream, payload: IDPayload
) -> RecordingPauseResumeResult:
    """Resume a paused leg recording"""
    out = await self._call("leg_record_resume", payload, result_model=RecordingPauseResumeResult)
    return out  # type: ignore[no-any-return]


EventStream.leg_record_resume = _vsi_leg_record_resume  # type: ignore[method-assign]


async def _vsi_leg_record_stop(self: EventStream, payload: IDPayload) -> RecordingStopLegResult:
    """Stop a leg recording"""
    out = await self._call("leg_record_stop", payload, result_model=RecordingStopLegResult)
    return out  # type: ignore[no-any-return]


EventStream.leg_record_stop = _vsi_leg_record_stop  # type: ignore[method-assign]


async def _vsi_room_record_stop(self: EventStream, payload: IDPayload) -> RecordingStopRoomResult:
    """Stop a room recording"""
    out = await self._call("room_record_stop", payload, result_model=RecordingStopRoomResult)
    return out  # type: ignore[no-any-return]


EventStream.room_record_stop = _vsi_room_record_stop  # type: ignore[method-assign]


async def _vsi_room_record_pause(
    self: EventStream, payload: IDPayload
) -> RecordingPauseResumeResult:
    """Pause a room recording"""
    out = await self._call("room_record_pause", payload, result_model=RecordingPauseResumeResult)
    return out  # type: ignore[no-any-return]


EventStream.room_record_pause = _vsi_room_record_pause  # type: ignore[method-assign]


async def _vsi_room_record_resume(
    self: EventStream, payload: IDPayload
) -> RecordingPauseResumeResult:
    """Resume a paused room recording"""
    out = await self._call("room_record_resume", payload, result_model=RecordingPauseResumeResult)
    return out  # type: ignore[no-any-return]


EventStream.room_record_resume = _vsi_room_record_resume  # type: ignore[method-assign]


async def _vsi_leg_play_start(
    self: EventStream, payload: PlaybackStartPayload
) -> PlaybackStartResult:
    """Start audio playback on a leg"""
    out = await self._call("leg_play_start", payload, result_model=PlaybackStartResult)
    return out  # type: ignore[no-any-return]


EventStream.leg_play_start = _vsi_leg_play_start  # type: ignore[method-assign]


async def _vsi_leg_play_stop(
    self: EventStream, payload: PlaybackTargetPayload
) -> PlaybackStopResult:
    """Stop a leg playback"""
    out = await self._call("leg_play_stop", payload, result_model=PlaybackStopResult)
    return out  # type: ignore[no-any-return]


EventStream.leg_play_stop = _vsi_leg_play_stop  # type: ignore[method-assign]


async def _vsi_room_play_start(
    self: EventStream, payload: PlaybackStartPayload
) -> PlaybackStartResult:
    """Start audio playback on a room mix"""
    out = await self._call("room_play_start", payload, result_model=PlaybackStartResult)
    return out  # type: ignore[no-any-return]


EventStream.room_play_start = _vsi_room_play_start  # type: ignore[method-assign]


async def _vsi_room_play_stop(
    self: EventStream, payload: PlaybackTargetPayload
) -> PlaybackStopResult:
    """Stop a room playback"""
    out = await self._call("room_play_stop", payload, result_model=PlaybackStopResult)
    return out  # type: ignore[no-any-return]


EventStream.room_play_stop = _vsi_room_play_stop  # type: ignore[method-assign]


async def _vsi_leg_play_volume(
    self: EventStream, payload: PlaybackVolumePayload
) -> VSIStatusResponse:
    """Adjust the volume of an active leg playback"""
    out = await self._call("leg_play_volume", payload, result_model=VSIStatusResponse)
    return out  # type: ignore[no-any-return]


EventStream.leg_play_volume = _vsi_leg_play_volume  # type: ignore[method-assign]


async def _vsi_room_play_volume(
    self: EventStream, payload: PlaybackVolumePayload
) -> VSIStatusResponse:
    """Adjust the volume of an active room playback"""
    out = await self._call("room_play_volume", payload, result_model=VSIStatusResponse)
    return out  # type: ignore[no-any-return]


EventStream.room_play_volume = _vsi_room_play_volume  # type: ignore[method-assign]


async def _vsi_leg_stt_start(self: EventStream, payload: STTStartPayload) -> STTStartLegResult:
    """Start speech-to-text on a leg"""
    out = await self._call("leg_stt_start", payload, result_model=STTStartLegResult)
    return out  # type: ignore[no-any-return]


EventStream.leg_stt_start = _vsi_leg_stt_start  # type: ignore[method-assign]


async def _vsi_room_stt_start(self: EventStream, payload: STTStartPayload) -> STTStartRoomResult:
    """Start speech-to-text on every participant of a room (auto-extends to legs that join later)"""
    out = await self._call("room_stt_start", payload, result_model=STTStartRoomResult)
    return out  # type: ignore[no-any-return]


EventStream.room_stt_start = _vsi_room_stt_start  # type: ignore[method-assign]


async def _vsi_leg_stt_stop(self: EventStream, payload: IDPayload) -> STTStopResult:
    """Stop speech-to-text on a leg"""
    out = await self._call("leg_stt_stop", payload, result_model=STTStopResult)
    return out  # type: ignore[no-any-return]


EventStream.leg_stt_stop = _vsi_leg_stt_stop  # type: ignore[method-assign]


async def _vsi_room_stt_stop(self: EventStream, payload: IDPayload) -> STTStopResult:
    """Stop speech-to-text on a room"""
    out = await self._call("room_stt_stop", payload, result_model=STTStopResult)
    return out  # type: ignore[no-any-return]


EventStream.room_stt_stop = _vsi_room_stt_stop  # type: ignore[method-assign]


async def _vsi_leg_tts(self: EventStream, payload: TTSStartPayload) -> TTSStartResult:
    """Synthesize speech and play it on a leg"""
    out = await self._call("leg_tts", payload, result_model=TTSStartResult)
    return out  # type: ignore[no-any-return]


EventStream.leg_tts = _vsi_leg_tts  # type: ignore[method-assign]


async def _vsi_room_tts(self: EventStream, payload: TTSStartPayload) -> TTSStartResult:
    """Synthesize speech and play it into a room mix"""
    out = await self._call("room_tts", payload, result_model=TTSStartResult)
    return out  # type: ignore[no-any-return]


EventStream.room_tts = _vsi_room_tts  # type: ignore[method-assign]


async def _vsi_leg_transfer(self: EventStream, payload: TransferLegPayload) -> TransferLegResult:
    """Initiate a SIP REFER transfer (blind or attended)"""
    out = await self._call("leg_transfer", payload, result_model=TransferLegResult)
    return out  # type: ignore[no-any-return]


EventStream.leg_transfer = _vsi_leg_transfer  # type: ignore[method-assign]


async def _vsi_leg_agent_elevenlabs(
    self: EventStream, payload: AgentElevenLabsPayload
) -> AgentStartLegResult:
    """Attach an ElevenLabs Conversational AI agent to a leg"""
    out = await self._call("leg_agent_elevenlabs", payload, result_model=AgentStartLegResult)
    return out  # type: ignore[no-any-return]


EventStream.leg_agent_elevenlabs = _vsi_leg_agent_elevenlabs  # type: ignore[method-assign]


async def _vsi_leg_agent_vapi(self: EventStream, payload: AgentVAPIPayload) -> AgentStartLegResult:
    """Attach a VAPI agent to a leg"""
    out = await self._call("leg_agent_vapi", payload, result_model=AgentStartLegResult)
    return out  # type: ignore[no-any-return]


EventStream.leg_agent_vapi = _vsi_leg_agent_vapi  # type: ignore[method-assign]


async def _vsi_leg_agent_pipecat(
    self: EventStream, payload: AgentPipecatPayload
) -> AgentStartLegResult:
    """Attach a Pipecat bot to a leg"""
    out = await self._call("leg_agent_pipecat", payload, result_model=AgentStartLegResult)
    return out  # type: ignore[no-any-return]


EventStream.leg_agent_pipecat = _vsi_leg_agent_pipecat  # type: ignore[method-assign]


async def _vsi_leg_agent_deepgram(
    self: EventStream, payload: AgentDeepgramPayload
) -> AgentStartLegResult:
    """Attach a Deepgram Voice Agent to a leg"""
    out = await self._call("leg_agent_deepgram", payload, result_model=AgentStartLegResult)
    return out  # type: ignore[no-any-return]


EventStream.leg_agent_deepgram = _vsi_leg_agent_deepgram  # type: ignore[method-assign]


async def _vsi_room_agent_elevenlabs(
    self: EventStream, payload: AgentElevenLabsPayload
) -> AgentStartRoomResult:
    """Attach an ElevenLabs Conversational AI agent to a room"""
    out = await self._call("room_agent_elevenlabs", payload, result_model=AgentStartRoomResult)
    return out  # type: ignore[no-any-return]


EventStream.room_agent_elevenlabs = _vsi_room_agent_elevenlabs  # type: ignore[method-assign]


async def _vsi_room_agent_vapi(
    self: EventStream, payload: AgentVAPIPayload
) -> AgentStartRoomResult:
    """Attach a VAPI agent to a room"""
    out = await self._call("room_agent_vapi", payload, result_model=AgentStartRoomResult)
    return out  # type: ignore[no-any-return]


EventStream.room_agent_vapi = _vsi_room_agent_vapi  # type: ignore[method-assign]


async def _vsi_room_agent_pipecat(
    self: EventStream, payload: AgentPipecatPayload
) -> AgentStartRoomResult:
    """Attach a Pipecat bot to a room"""
    out = await self._call("room_agent_pipecat", payload, result_model=AgentStartRoomResult)
    return out  # type: ignore[no-any-return]


EventStream.room_agent_pipecat = _vsi_room_agent_pipecat  # type: ignore[method-assign]


async def _vsi_room_agent_deepgram(
    self: EventStream, payload: AgentDeepgramPayload
) -> AgentStartRoomResult:
    """Attach a Deepgram Voice Agent to a room"""
    out = await self._call("room_agent_deepgram", payload, result_model=AgentStartRoomResult)
    return out  # type: ignore[no-any-return]


EventStream.room_agent_deepgram = _vsi_room_agent_deepgram  # type: ignore[method-assign]


async def _vsi_leg_agent_stop(self: EventStream, payload: IDPayload) -> AgentStopResult:
    """Detach the agent attached to a leg"""
    out = await self._call("leg_agent_stop", payload, result_model=AgentStopResult)
    return out  # type: ignore[no-any-return]


EventStream.leg_agent_stop = _vsi_leg_agent_stop  # type: ignore[method-assign]


async def _vsi_room_agent_stop(self: EventStream, payload: IDPayload) -> AgentStopResult:
    """Detach the agent attached to a room"""
    out = await self._call("room_agent_stop", payload, result_model=AgentStopResult)
    return out  # type: ignore[no-any-return]


EventStream.room_agent_stop = _vsi_room_agent_stop  # type: ignore[method-assign]


async def _vsi_leg_agent_message(
    self: EventStream, payload: AgentMessagePayload
) -> AgentMessageResult:
    """Inject a text message into a leg agent session"""
    out = await self._call("leg_agent_message", payload, result_model=AgentMessageResult)
    return out  # type: ignore[no-any-return]


EventStream.leg_agent_message = _vsi_leg_agent_message  # type: ignore[method-assign]


async def _vsi_room_agent_message(
    self: EventStream, payload: AgentMessagePayload
) -> AgentMessageResult:
    """Inject a text message into a room agent session"""
    out = await self._call("room_agent_message", payload, result_model=AgentMessageResult)
    return out  # type: ignore[no-any-return]


EventStream.room_agent_message = _vsi_room_agent_message  # type: ignore[method-assign]
