"""GENERATED by tools/generate.py from VoiceBlender openapi.yaml + asyncapi.yaml.

DO NOT EDIT — run ``make generate`` to regenerate.
"""

from __future__ import annotations

from voiceblender._client import Client
from voiceblender._models import Leg, Room
from voiceblender._requests import ICECandidateInit, WebRTCOfferRequest
from voiceblender._responses import StatusResponse
from voiceblender._responses_extra import ICECandidatesResponse, WebRTCOfferResponse

__all__: list[str] = []

# WebRTC operations — bound onto Client / Leg / Room by class assignment.


async def _leg_get_ice_candidates(self: Leg) -> ICECandidatesResponse:
    """Get server-side ICE candidates for a WebRTC leg (trickle ICE)"""
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "GET", f"/legs/{self.id}/ice-candidates", out_model=ICECandidatesResponse
    )
    assert out is not None, "getICECandidates" + ": empty response"
    return out


Leg.get_ice_candidates = _leg_get_ice_candidates  # type: ignore[method-assign]


async def _leg_add_ice_candidate(self: Leg, req: ICECandidateInit) -> StatusResponse:
    """Send a remote ICE candidate to a WebRTC leg (trickle ICE)"""
    if self._client is None:
        raise RuntimeError(f"{type(self).__name__} not bound to a Client")
    out = await self._client._do(
        "POST", f"/legs/{self.id}/ice-candidates", body=req, out_model=StatusResponse
    )
    return out if out is not None else StatusResponse(status="ok")


Leg.add_ice_candidate = _leg_add_ice_candidate  # type: ignore[method-assign]


async def _client_webrtc_offer(self: Client, req: WebRTCOfferRequest) -> WebRTCOfferResponse:
    """Establish a WebRTC leg via SDP offer/answer"""
    out = await self._do("POST", "/webrtc/offer", body=req, out_model=WebRTCOfferResponse)
    assert out is not None, "webrtcOffer" + ": empty response"
    return out


Client.webrtc_offer = _client_webrtc_offer  # type: ignore[method-assign]

_unused: tuple = (Leg, Room)
